// FaithFit Daily Bread — expansion library #2.
// Adds ~30 more passage-based readings: OT figures (Gideon → Malachi),
// more of Jesus' ministry, Acts, and Christian living. Same schema as
// dailyBread.ts. Prayers auto-close with "In Jesus' name, Amen. 🙏🏽".

import { ensurePrayerEnding } from './journeys';
import type { DailyBreadReading } from './dailyBread';

const r = (e: Omit<DailyBreadReading, 'prayer'> & { prayer: string }): DailyBreadReading => ({
  ...e,
  prayer: ensurePrayerEnding(e.prayer),
});

const BG = {
  judges: { author: 'Traditionally Samuel, compiled from earlier records', when: 'Events ~1380–1050 BC', audience: 'Israel under the monarchy looking back at the chaos before the king', whyWritten: 'To show what happens when God\'s people forget Him — and how He keeps rescuing them anyway.' },
  samuel1: { author: 'Likely Samuel, Nathan, and Gad', when: 'Events ~1100–1010 BC', audience: 'Israel learning what kind of king God chooses', whyWritten: 'To trace God\'s hand from Hannah\'s prayer to David\'s throne.' },
  nehemiah: { author: 'Nehemiah, with editorial help', when: 'Around 445 BC', audience: 'Jews returning from exile rebuilding Jerusalem', whyWritten: 'To show how God uses ordinary leadership, prayer, and grit to restore His people.' },
  ezra: { author: 'Ezra the priest-scribe', when: 'Around 458 BC', audience: 'The post-exile community in Jerusalem', whyWritten: 'To call God\'s people back to Scripture and to wholehearted obedience.' },
  isaiah: { author: 'Isaiah the prophet', when: 'Around 740–680 BC', audience: 'Judah, drifting from God and facing exile', whyWritten: 'To warn, comfort, and point ahead to the coming Servant-King.' },
  jeremiah: { author: 'Jeremiah, the "weeping prophet"', when: 'Around 627–580 BC', audience: 'Judah on the brink of Babylonian exile', whyWritten: 'To call God\'s people to repentance and promise a new covenant.' },
  ezekiel: { author: 'Ezekiel, a priest exiled to Babylon', when: 'Around 593–571 BC', audience: 'Jewish exiles wondering if God had forgotten them', whyWritten: 'To show that God is still on His throne and will breathe life into dead bones.' },
  hosea: { author: 'Hosea the prophet', when: 'Around 750 BC', audience: 'The northern kingdom of Israel chasing other gods', whyWritten: 'To picture God\'s relentless covenant love through a heartbreaking marriage.' },
  malachi: { author: 'Malachi, the last OT prophet', when: 'Around 430 BC', audience: 'A spiritually-bored post-exile community', whyWritten: 'To wake God\'s people up before 400 years of silence — and the coming Messenger.' },
  matthew: { author: 'Matthew, a former tax collector turned apostle', when: 'Around AD 50–70', audience: 'Primarily Jewish believers needing to see Jesus as the promised Messiah', whyWritten: 'To show Jesus as the King who fulfills the Old Testament.' },
  mark: { author: 'John Mark, traveling companion of Peter', when: 'Around AD 60', audience: 'Roman Christians under pressure for their faith', whyWritten: 'To show Jesus as the powerful, suffering Son of God worth following.' },
  luke: { author: 'Luke, a careful historian and physician', when: 'Around AD 60', audience: 'Theophilus and the wider church — many outsiders coming home to God', whyWritten: 'To give an orderly account of who Jesus is and the people He came for.' },
  john: { author: 'John, the apostle Jesus loved', when: 'Late first century', audience: 'A mixed church of Jews and Gentiles', whyWritten: 'That you might believe Jesus is the Christ and have life in His name.' },
  acts: { author: 'Luke, the physician-historian', when: 'Around AD 62', audience: 'Theophilus and the early church', whyWritten: 'To show how the risen Jesus built His church through His Spirit.' },
  paulEph: { author: 'Paul, writing from prison', when: 'Around AD 60–62', audience: 'The church in Ephesus and surrounding cities', whyWritten: 'To remind believers who they are in Christ and how the church lives it out.' },
  paulGal: { author: 'Paul', when: 'Around AD 48–55', audience: 'Churches in Galatia drifting back into legalism', whyWritten: 'To defend the gospel of grace — Christ alone saves.' },
  paul1Cor: { author: 'Paul', when: 'Around AD 55', audience: 'A messy, gifted, divided church in Corinth', whyWritten: 'To call the church back to the cross and to real love.' },
  hebrews: { author: 'Unknown — possibly Apollos or Barnabas', when: 'Before AD 70', audience: 'Jewish believers tempted to go back to the old system', whyWritten: 'To show that Jesus is greater — and worth holding on to.' },
  james: { author: 'James, the half-brother of Jesus', when: 'Around AD 45–49', audience: 'Scattered Jewish Christians', whyWritten: 'To show what real, working faith looks like in everyday life.' },
};

export const dailyBreadExpansion2: DailyBreadReading[] = [
  // ============ OLD TESTAMENT FIGURES ============
  r({
    id: 'gideon-fleece',
    theme: 'God uses the weakest one in the room',
    oneLine: 'Gideon was hiding in a winepress when God called him a mighty warrior.',
    passageRef: 'Judges 6:11-16',
    passageTitle: 'God calls Gideon',
    category: 'narrative',
    characters: ['Gideon', 'The angel of the LORD'],
    verses: [
      { v: 11, text: 'And there came an angel of the LORD, and sat under an oak which was in Ophrah... and his son Gideon threshed wheat by the winepress, to hide it from the Midianites.' },
      { v: 12, text: 'And the angel of the LORD appeared unto him, and said unto him, The LORD is with thee, thou mighty man of valour.' },
      { v: 14, text: 'And the LORD looked upon him, and said, Go in this thy might, and save Israel from the hand of the Midianites: have not I sent thee?' },
      { v: 15, text: 'And he said unto him, Oh my Lord, wherewith shall I save Israel? behold, my family is poor in Manasseh, and I am the least in my father\'s house.' },
      { v: 16, text: 'And the LORD said unto him, Surely I will be with thee, and thou shalt smite the Midianites as one man.' },
    ],
    whatsHappening: 'Israel has been crushed by Midianite raiders for seven years. Gideon — the least son of a poor family — is secretly threshing wheat in a winepress so he won\'t be seen. God calls this scared, hiding man a "mighty man of valour" and sends him to save Israel.',
    aboutGod: 'God sees who you will be before you see it yourself. He doesn\'t recruit the qualified — He qualifies the called. And His "I will be with thee" is enough.',
    aboutJesus: 'Gideon delivered a generation; Jesus delivers forever. Where Gideon questioned "wherewith shall I save?" — Jesus answered with the cross. He calls weak people to follow Him, and goes with them.',
    background: BG.judges,
    reflection: [
      'Where do you feel like the least one in the room?',
      'What does it change to hear God call you what He sees, not what you feel?',
      'What might "go in this thy might" look like for you this week?',
    ],
    prayer: 'Lord, I feel small and unqualified. Thank You that You see me, You call me, and You go with me. Help me take the next step You\'re sending me on.',
    actionStep: 'Name one thing you\'ve been avoiding because you feel inadequate. Tell God, "I\'ll take one step today because You go with me," and do it.',
    quickTakeaway: 'God calls who He calls — and He goes with them. Your "least" is not too small for Him.',
  }),

  r({
    id: 'deborah-judge',
    theme: 'God raises up unlikely leaders',
    oneLine: 'When the men hesitated, Deborah went — and trusted God for the rest.',
    passageRef: 'Judges 4:4-9',
    passageTitle: 'Deborah leads Israel',
    category: 'narrative',
    characters: ['Deborah', 'Barak'],
    verses: [
      { v: 4, text: 'And Deborah, a prophetess... she judged Israel at that time.' },
      { v: 6, text: 'And she sent and called Barak... and said unto him, Hath not the LORD God of Israel commanded, saying, Go and draw toward mount Tabor...' },
      { v: 7, text: 'And I will draw unto thee... Sisera, the captain of Jabin\'s army... and I will deliver him into thine hand.' },
      { v: 8, text: 'And Barak said unto her, If thou wilt go with me, then I will go: but if thou wilt not go with me, then I will not go.' },
      { v: 9, text: 'And she said, I will surely go with thee... And Deborah arose, and went with Barak to Kedesh.' },
    ],
    whatsHappening: 'Israel has been oppressed by Jabin\'s army for twenty years. Deborah — prophet, judge, and the only woman to hold all three offices — hears God and calls Barak to lead the army. He won\'t go without her. She goes.',
    aboutGod: 'God raises up leaders His way — not by gender, status, or polish, but by faith and faithfulness. He uses whoever will say yes.',
    aboutJesus: 'Deborah pointed Israel back to obedience; Jesus is the greater Judge who delivers His people from a bigger enemy. He still calls ordinary believers — men and women — to lead in faith.',
    background: BG.judges,
    reflection: [
      'Whose faith has carried yours in a hard season?',
      'Where might God be calling you to "go" while others hesitate?',
      'How does Deborah\'s example shape the way you see your own role in God\'s story?',
    ],
    prayer: 'Lord, give me courage to obey when others hesitate, and humility to follow when You raise up unlikely leaders around me. I want to be useful to Your kingdom.',
    actionStep: 'Encourage one believer who is doing hard, faithful work in the background today. Tell them you see God using them.',
    quickTakeaway: 'God uses whoever will say yes. Be that person today.',
  }),

  r({
    id: 'samson-restored',
    theme: 'Even after we waste our strength, God answers',
    oneLine: 'Samson\'s last prayer was his most honest one.',
    passageRef: 'Judges 16:23-30',
    passageTitle: 'Samson\'s final prayer',
    category: 'narrative',
    characters: ['Samson', 'The Philistines'],
    verses: [
      { v: 25, text: 'And it came to pass... that they said, Call for Samson, that he may make us sport.' },
      { v: 28, text: 'And Samson called unto the LORD, and said, O Lord GOD, remember me, I pray thee, and strengthen me, I pray thee, only this once, O God...' },
      { v: 29, text: 'And Samson took hold of the two middle pillars upon which the house stood...' },
      { v: 30, text: 'And Samson said, Let me die with the Philistines. And he bowed himself with all his might; and the house fell upon the lords...' },
    ],
    whatsHappening: 'Samson — given supernatural strength from birth — has squandered it on lust and pride. Blinded and chained, he is paraded as entertainment. In his lowest moment, broken and humbled, he finally prays a simple, dependent prayer. God answers.',
    aboutGod: 'God\'s grace is not earned by a clean record. He hears the prayers of people who have wasted their gifts and still come back to Him.',
    aboutJesus: 'Samson died bringing down a temple of false gods; Jesus died bringing down sin itself. Where Samson\'s last act killed his enemies, Jesus\' last act saved His. Both teach us: God\'s deliverers come through weakness.',
    background: BG.judges,
    reflection: [
      'Where in your story have you wasted what God gave you?',
      'What does it mean that God still answered Samson?',
      'What honest, dependent prayer do you need to pray today?',
    ],
    prayer: 'Lord, I have not always stewarded what You gave me. Remember me. Strengthen me. Use even what is left for Your glory.',
    actionStep: 'Pray a single sentence with your whole heart today: "Lord, remember me." Then listen.',
    quickTakeaway: 'It is never too late to turn back to the God who still answers.',
  }),

  r({
    id: 'hannah-prayer',
    theme: 'Honest prayer from a breaking heart',
    oneLine: 'Hannah brought God her tears — and God brought her a son.',
    passageRef: '1 Samuel 1:10-18',
    passageTitle: 'Hannah pours out her soul',
    category: 'narrative',
    characters: ['Hannah', 'Eli the priest'],
    verses: [
      { v: 10, text: 'And she was in bitterness of soul, and prayed unto the LORD, and wept sore.' },
      { v: 11, text: 'And she vowed a vow, and said, O LORD of hosts, if thou wilt indeed look on the affliction of thine handmaid...' },
      { v: 15, text: '...I am a woman of a sorrowful spirit... but have poured out my soul before the LORD.' },
      { v: 17, text: 'Then Eli answered and said, Go in peace: and the God of Israel grant thee thy petition...' },
      { v: 18, text: '...So the woman went her way, and did eat, and her countenance was no more sad.' },
    ],
    whatsHappening: 'Hannah is barren in a culture that measured a woman\'s worth by her children. Year after year of grief. At the tabernacle she finally breaks — praying with such intensity the priest thinks she\'s drunk. She leaves before God answers, but her face is already changed.',
    aboutGod: 'God welcomes raw, undignified prayer. He is not embarrassed by tears. He hears the woman everyone else misunderstands.',
    aboutJesus: 'Hannah\'s answered prayer — Samuel — opened the door for David, and through David, for Jesus. Honest prayer from one hurting woman moved redemptive history forward.',
    background: BG.samuel1,
    reflection: [
      'When was the last time you let yourself pray without polish?',
      'What grief have you been editing before bringing it to God?',
      'Hannah went home before God answered, and yet her face had changed. Why?',
    ],
    prayer: 'Lord, here is what I\'ve been holding back. I pour it out — the grief, the longing, the fear. Hear me. And whether You answer the way I hope or not, change my face by Your presence.',
    actionStep: 'Tell God one thing you\'ve been too proud or too tired to say out loud. Use Hannah\'s words: "I have poured out my soul before the LORD."',
    quickTakeaway: 'You don\'t have to dress up your prayers. Honest is enough.',
  }),

  r({
    id: 'nehemiah-walls',
    theme: 'Prayer plus work plus courage',
    oneLine: 'Nehemiah prayed to heaven and then picked up tools.',
    passageRef: 'Nehemiah 2:4-8',
    passageTitle: 'Nehemiah rebuilds Jerusalem',
    category: 'narrative',
    characters: ['Nehemiah', 'King Artaxerxes'],
    verses: [
      { v: 4, text: 'Then the king said unto me, For what dost thou make request? So I prayed to the God of heaven.' },
      { v: 5, text: 'And I said unto the king, If it please the king... that thou wouldest send me unto Judah, unto the city of my fathers\' sepulchres, that I may build it.' },
      { v: 8, text: '...And the king granted me, according to the good hand of my God upon me.' },
    ],
    whatsHappening: 'Nehemiah is a Jewish cupbearer in the Persian palace. He hears Jerusalem\'s walls are rubble and weeps. He prays for months. When the king asks what he wants, Nehemiah shoots a split-second prayer to heaven and then makes a clear, courageous ask — and gets everything he needs to rebuild.',
    aboutGod: 'God moves the hearts of kings. He fits long prayer and quick prayer together. And He gives wisdom and favor to those willing to risk and to work.',
    aboutJesus: 'Nehemiah rebuilt a city; Jesus rebuilds people. Both require prayer and willingness. Christ is the greater Nehemiah, taking what is broken and making it strong again.',
    background: BG.nehemiah,
    reflection: [
      'What rubble in your life are you grieving but not yet praying over?',
      'Where do you need a "prayer in the moment" before you speak?',
      'What courageous ask is God nudging you toward?',
    ],
    prayer: 'God of heaven, give me both the prayer and the courage to work. Move the hearts I cannot move. Rebuild what is broken in me and around me.',
    actionStep: 'Make one specific, courageous ask today — of God, and of a person — about something broken you want to see rebuilt.',
    quickTakeaway: 'Pray hard. Then act. God moves through both.',
  }),

  r({
    id: 'ezra-scripture',
    theme: 'Scripture is meant to be read, understood, lived',
    oneLine: 'When God\'s people heard the Word read clearly, they wept — then they obeyed.',
    passageRef: 'Nehemiah 8:5-12',
    passageTitle: 'Ezra reads the Law',
    category: 'narrative',
    characters: ['Ezra', 'The people of Israel'],
    verses: [
      { v: 5, text: 'And Ezra opened the book in the sight of all the people... and when he opened it, all the people stood up:' },
      { v: 8, text: 'So they read in the book in the law of God distinctly, and gave the sense, and caused them to understand the reading.' },
      { v: 9, text: '...This day is holy unto the LORD your God; mourn not, nor weep. For all the people wept, when they heard the words of the law.' },
      { v: 10, text: '...for the joy of the LORD is your strength.' },
    ],
    whatsHappening: 'After exile, the wall is rebuilt and the people gather. Ezra reads the Law from morning until midday — and the Levites help everyone understand it. The people weep. Then they\'re told: the right response now is joy.',
    aboutGod: 'God\'s Word is meant to be heard, explained, and obeyed — not just admired. When His people meet His Word honestly, He turns sorrow into joy.',
    aboutJesus: 'Jesus opened the Scriptures on the road to Emmaus and on every page about Himself. He is the Word made flesh — and through Him, every reading becomes living.',
    background: BG.ezra,
    reflection: [
      'When did Scripture last move you to honest tears — or honest joy?',
      'Is there a verse you\'ve been hearing without yet understanding?',
      'What would it look like to read God\'s Word "distinctly" this week?',
    ],
    prayer: 'Lord, open the Book to me. Help me hear, understand, and obey. Turn my sorrow into the joy of knowing You.',
    actionStep: 'Pick one chapter. Read it slowly out loud. Then write one sentence: "What is God saying to me?"',
    quickTakeaway: 'The Word read with attention changes lives. Open it today.',
  }),

  r({
    id: 'isaiah-call',
    theme: 'A holy God meets an undone man',
    oneLine: '"Holy, holy, holy" — and then, "Here am I; send me."',
    passageRef: 'Isaiah 6:1-8',
    passageTitle: 'Isaiah sees the Lord',
    category: 'narrative',
    characters: ['Isaiah', 'The Lord', 'Seraphim'],
    verses: [
      { v: 1, text: 'In the year that king Uzziah died I saw also the Lord sitting upon a throne, high and lifted up, and his train filled the temple.' },
      { v: 3, text: 'And one cried unto another, and said, Holy, holy, holy, is the LORD of hosts: the whole earth is full of his glory.' },
      { v: 5, text: 'Then said I, Woe is me! for I am undone; because I am a man of unclean lips...' },
      { v: 7, text: '...thine iniquity is taken away, and thy sin purged.' },
      { v: 8, text: 'Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me.' },
    ],
    whatsHappening: 'King Uzziah has died — a stable era is gone. In that uncertainty, Isaiah sees the real King on the real throne. He undone. A seraph brings a coal from the altar — sin atoned. Then God asks who will go, and Isaiah volunteers.',
    aboutGod: 'God is holy in a way that exposes us — and merciful in a way that cleanses us. He invites the forgiven to go on His behalf.',
    aboutJesus: 'John 12:41 says Isaiah saw Jesus\' glory. The coal from the altar pictures the cross — sin truly removed. Only after we know we\'re forgiven can we say "send me" without fear.',
    background: BG.isaiah,
    reflection: [
      'When did you last sense how holy God really is?',
      'What "unclean lips" do you need to bring to the altar?',
      'If forgiveness is settled in Christ, what is keeping you from saying "send me"?',
    ],
    prayer: 'Holy God, I am undone before You. Thank You that the cross has done what no coal could — my sin is purged in Jesus. Here am I; send me.',
    actionStep: 'Whisper "Here am I; send me" before your day starts. Then ask God what one small "go" looks like today.',
    quickTakeaway: 'Holiness humbles us. Mercy sends us.',
  }),

  r({
    id: 'jeremiah-potter',
    theme: 'God reshapes what we surrender',
    oneLine: 'In the Potter\'s hand, marred clay still becomes something good.',
    passageRef: 'Jeremiah 18:1-6',
    passageTitle: 'The potter and the clay',
    category: 'narrative',
    characters: ['Jeremiah', 'The Lord'],
    verses: [
      { v: 1, text: 'The word which came to Jeremiah from the LORD, saying,' },
      { v: 2, text: 'Arise, and go down to the potter\'s house, and there I will cause thee to hear my words.' },
      { v: 3, text: 'Then I went down to the potter\'s house, and, behold, he wrought a work on the wheels.' },
      { v: 4, text: 'And the vessel that he made of clay was marred in the hand of the potter: so he made it again another vessel, as seemed good to the potter to make it.' },
      { v: 6, text: '...as the clay is in the potter\'s hand, so are ye in mine hand, O house of Israel.' },
    ],
    whatsHappening: 'Jeremiah ministers to a stubborn nation on the edge of exile. God sends him to a working potter as a parable. The clay collapses — but the potter doesn\'t throw it out. He reshapes it.',
    aboutGod: 'God doesn\'t discard marred lives. He reshapes them. Surrender is not loss — it\'s the condition for becoming what He intended.',
    aboutJesus: 'Jesus is both Potter and Vessel — He took on flesh to remake ours. In Him, the marred becomes new (2 Corinthians 5:17).',
    background: BG.jeremiah,
    reflection: [
      'Where do you feel "marred" right now?',
      'What part of your life are you keeping off the wheel?',
      'How is God reshaping you in this season, even through pain?',
    ],
    prayer: 'Potter, I bring You the marred parts of my life. Make me again — into what seems good to You. I trust Your hands.',
    actionStep: 'Open your hands physically as you pray today. Name one area you\'re placing back on God\'s wheel.',
    quickTakeaway: 'You\'re not discarded. You\'re being reshaped.',
  }),

  r({
    id: 'ezekiel-dry-bones',
    theme: 'God brings life into what looks dead',
    oneLine: 'A valley of dry bones stood up and breathed — because God said so.',
    passageRef: 'Ezekiel 37:1-10',
    passageTitle: 'The valley of dry bones',
    category: 'narrative',
    characters: ['Ezekiel', 'The Lord'],
    verses: [
      { v: 1, text: 'The hand of the LORD was upon me... and set me down in the midst of the valley which was full of bones,' },
      { v: 3, text: 'And he said unto me, Son of man, can these bones live? And I answered, O Lord GOD, thou knowest.' },
      { v: 4, text: '...O ye dry bones, hear the word of the LORD.' },
      { v: 5, text: 'Thus saith the Lord GOD unto these bones; Behold, I will cause breath to enter into you, and ye shall live:' },
      { v: 10, text: '...and the breath came into them, and they lived, and stood up upon their feet, an exceeding great army.' },
    ],
    whatsHappening: 'Ezekiel is in exile speaking to crushed people. God shows him a valley of bones — picture of Israel\'s dead hope. He commands Ezekiel to prophesy. The bones rattle, knit together, take breath, and stand.',
    aboutGod: 'God is in the business of resurrection. He speaks life where there is none. He does not need raw material to work with — only His word.',
    aboutJesus: 'Jesus stood at Lazarus\' tomb and called him out. He still calls dead hearts to life by the gospel. What Ezekiel saw in vision, Jesus accomplishes by His resurrection (Romans 6:4).',
    background: BG.ezekiel,
    reflection: [
      'What in your life feels like a valley of dry bones right now?',
      'Where have you stopped asking God because you assumed it\'s too late?',
      'What might happen if you "prophesied" — spoke God\'s promises — over that area this week?',
    ],
    prayer: 'Lord, You alone know if these bones can live. Speak Your word. Breathe Your Spirit. Raise up what I have written off.',
    actionStep: 'Name one "dead" situation. Speak one specific promise of God over it out loud today.',
    quickTakeaway: 'Nothing is too dead for the God who raises bones — and raises Jesus.',
  }),

  r({
    id: 'hosea-relentless-love',
    theme: 'God\'s love that will not let us go',
    oneLine: 'God told a prophet to buy back his wayward wife — to picture how He loves us.',
    passageRef: 'Hosea 3:1-5',
    passageTitle: 'Hosea redeems Gomer',
    category: 'narrative',
    characters: ['Hosea', 'Gomer', 'The Lord'],
    verses: [
      { v: 1, text: 'Then said the LORD unto me, Go yet, love a woman beloved of her friend, yet an adulteress, according to the love of the LORD toward the children of Israel...' },
      { v: 2, text: 'So I bought her to me for fifteen pieces of silver, and for an homer of barley...' },
      { v: 3, text: 'And I said unto her, Thou shalt abide for me many days... so will I also be for thee.' },
      { v: 5, text: 'Afterward shall the children of Israel return, and seek the LORD their God, and David their king...' },
    ],
    whatsHappening: 'God tells Hosea to marry Gomer, who repeatedly leaves him. When she ends up enslaved, God tells Hosea to buy her back. The marriage is a living parable: Israel keeps walking away, and God keeps paying to bring her home.',
    aboutGod: 'God\'s love is covenantal, not casual. He does not stop loving the people who keep wandering. He pays the price to bring them home.',
    aboutJesus: 'Hosea bought Gomer with silver and barley; Jesus bought us with His blood (1 Peter 1:18-19). The cross is God still saying, "I will be for thee."',
    background: BG.hosea,
    reflection: [
      'Where have you wandered? How does it land that God came after you?',
      'How does God\'s love in Hosea compare to how you usually picture His love?',
      'Who in your life needs you to picture this kind of love for them?',
    ],
    prayer: 'Lord, I have wandered. Thank You that You bought me back at the cross. I want to come home today and stay.',
    actionStep: 'Write down one specific way you\'ve drifted. Then write one specific way you\'ll come home this week.',
    quickTakeaway: 'God\'s love does not give up. He paid to bring you home.',
  }),

  r({
    id: 'malachi-return',
    theme: 'Return to God — and watch the windows of heaven open',
    oneLine: '"Return unto me, and I will return unto you."',
    passageRef: 'Malachi 3:7-12',
    passageTitle: 'Return and be blessed',
    category: 'teaching',
    characters: ['The Lord', 'Post-exile Israel'],
    verses: [
      { v: 7, text: '...Return unto me, and I will return unto you, saith the LORD of hosts. But ye said, Wherein shall we return?' },
      { v: 8, text: 'Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings.' },
      { v: 10, text: 'Bring ye all the tithes into the storehouse... and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing...' },
    ],
    whatsHappening: 'After exile, the people are spiritually bored. Worship is half-hearted, giving is stingy, marriages are crumbling. God says: stop pretending — return to Me. He even invites them to test His faithfulness in giving.',
    aboutGod: 'God is generous beyond measure and welcomes those who turn back. He doesn\'t need our offerings; He wants our hearts. And He proves Himself faithful when we trust Him.',
    aboutJesus: 'Malachi closes the Old Testament promising a Messenger to prepare the way. That promise becomes flesh in Jesus, the one who says, "Come unto me" (Matthew 11:28). The whole Bible is God calling us home.',
    background: BG.malachi,
    reflection: [
      'In what area have you grown bored or stingy with God?',
      'What would "return" look like for you this week — practically?',
      'Where do you need to trust God\'s generosity enough to obey?',
    ],
    prayer: 'Lord, I return. Forgive my half-hearted faith. I trust Your generosity more than my fear. Open my hands and open Your windows.',
    actionStep: 'Identify one area where you\'ve held back from God — time, money, attention. Take one tangible step of return this week.',
    quickTakeaway: 'Return to God. He returns to you. Always.',
  }),

  // ============ JESUS ============
  r({
    id: 'transfiguration',
    theme: 'A glimpse of glory before the cross',
    oneLine: 'For one moment, three friends saw who Jesus really is.',
    passageRef: 'Matthew 17:1-9',
    passageTitle: 'The Transfiguration',
    category: 'narrative',
    characters: ['Jesus', 'Peter', 'James', 'John', 'Moses', 'Elijah'],
    verses: [
      { v: 1, text: 'And after six days Jesus taketh Peter, James, and John his brother, and bringeth them up into an high mountain apart,' },
      { v: 2, text: 'And was transfigured before them: and his face did shine as the sun, and his raiment was white as the light.' },
      { v: 3, text: 'And, behold, there appeared unto them Moses and Elias talking with him.' },
      { v: 5, text: '...behold a voice out of the cloud, which said, This is my beloved Son, in whom I am well pleased; hear ye him.' },
      { v: 7, text: 'And Jesus came and touched them, and said, Arise, and be not afraid.' },
    ],
    whatsHappening: 'Right after Jesus tells His disciples He must die, He takes three of them up a mountain. There His full glory shines through. Moses (the Law) and Elijah (the Prophets) appear and speak with Him. The Father\'s voice repeats what He said at Jesus\' baptism: hear Him.',
    aboutGod: 'God authenticates His Son in front of trusted witnesses. He shows that all the Law and Prophets point to Jesus. And He still touches frightened people and says, "Arise, and be not afraid."',
    aboutJesus: 'The glory the disciples briefly saw is the glory Jesus had with the Father before the world began (John 17:5) — and the glory He returned to after the resurrection. He veiled it to walk our roads and die our death.',
    background: BG.matthew,
    reflection: [
      'When have you sensed a "mountain moment" with Jesus?',
      'Why did Jesus tell them to keep it quiet until after the resurrection?',
      'What does the Father\'s command — "hear ye him" — mean for you this week?',
    ],
    prayer: 'Jesus, I want to see You for who You really are. Open my eyes to Your glory. Help me listen to You above every other voice.',
    actionStep: 'Pick one teaching of Jesus this week and read it three times — slowly. Ask, "Father, help me hear Him."',
    quickTakeaway: 'Jesus is the One the Father says to listen to. Tune your ear to Him today.',
  }),

  r({
    id: 'widows-mite',
    theme: 'God measures the heart, not the amount',
    oneLine: 'The richest gift in the temple that day was two small coins.',
    passageRef: 'Mark 12:41-44',
    passageTitle: 'The widow\'s offering',
    category: 'narrative',
    characters: ['Jesus', 'The disciples', 'A poor widow'],
    verses: [
      { v: 41, text: 'And Jesus sat over against the treasury, and beheld how the people cast money into the treasury: and many that were rich cast in much.' },
      { v: 42, text: 'And there came a certain poor widow, and she threw in two mites, which make a farthing.' },
      { v: 43, text: '...Verily I say unto you, That this poor widow hath cast more in, than all they which have cast into the treasury:' },
      { v: 44, text: 'For all they did cast in of their abundance; but she of her want did cast in all that she had, even all her living.' },
    ],
    whatsHappening: 'Jesus sits and watches people give. The big donors are obvious. A widow drops in two tiny copper coins — the smallest currency. Jesus calls His disciples close to teach them: she just gave more than everyone else.',
    aboutGod: 'God sees what no one else notices. He measures by what we hold back, not by what we hand over. Faith-filled smallness moves Him more than impressive surplus.',
    aboutJesus: 'Jesus would soon give "all His living" on the cross — total self-gift. The widow was a small picture of the love Jesus was about to live out.',
    background: BG.mark,
    reflection: [
      'What is your "two mites" — small but costly — that God is inviting you to give?',
      'Where have you given out of abundance but not yet out of trust?',
      'How does it change you to know Jesus notices what no one else does?',
    ],
    prayer: 'Jesus, I want my offering of time, money, and life to come from trust, not leftovers. You see me. Help me give like the widow — because I trust You like she did.',
    actionStep: 'Give something today that actually costs you a little — time, money, or attention — and tell God it\'s for Him.',
    quickTakeaway: 'God doesn\'t weigh the gift. He weighs the heart.',
  }),

  r({
    id: 'blind-bartimaeus',
    theme: 'Keep crying out until Jesus stops',
    oneLine: 'A blind beggar refused to be silenced — and Jesus stood still.',
    passageRef: 'Mark 10:46-52',
    passageTitle: 'Jesus heals Bartimaeus',
    category: 'narrative',
    characters: ['Jesus', 'Bartimaeus', 'The crowd'],
    verses: [
      { v: 47, text: 'And when he heard that it was Jesus of Nazareth, he began to cry out, and say, Jesus, thou Son of David, have mercy on me.' },
      { v: 48, text: 'And many charged him that he should hold his peace: but he cried the more a great deal, Thou son of David, have mercy on me.' },
      { v: 49, text: 'And Jesus stood still, and commanded him to be called...' },
      { v: 51, text: 'And Jesus answered and said unto him, What wilt thou that I should do unto thee? The blind man said unto him, Lord, that I might receive my sight.' },
      { v: 52, text: 'And Jesus said unto him, Go thy way; thy faith hath made thee whole. And immediately he received his sight, and followed Jesus in the way.' },
    ],
    whatsHappening: 'Bartimaeus is a blind beggar in Jericho. As Jesus passes through, he yells. People tell him to be quiet. He yells louder. Jesus stops the procession, calls him over, asks what he wants, and heals him. The healed man immediately follows.',
    aboutGod: 'God hears the cries the crowd tries to silence. He stops for one person. He asks us to name what we actually want.',
    aboutJesus: 'Bartimaeus called Jesus "Son of David" — a Messianic title. He saw who Jesus was before he saw anything else. Jesus is the kind of King who stops for the one no one else stops for.',
    background: BG.mark,
    reflection: [
      'What are you whispering to God that you need to say loudly?',
      'If Jesus asked you today, "What do you want Me to do for you?" — what is your honest answer?',
      'Bartimaeus followed Jesus the moment he could see. What "next step of following" is in front of you?',
    ],
    prayer: 'Jesus, Son of David, have mercy on me. I want to see — to see You, to see myself rightly, to see the next step. Open my eyes and let me follow.',
    actionStep: 'Pray Bartimaeus\' prayer word for word today — out loud — three times. Then sit and listen.',
    quickTakeaway: 'Jesus stops for the one who keeps crying out. Do not stop.',
  }),

  r({
    id: 'centurion-faith',
    theme: 'Faith Jesus marvels at',
    oneLine: 'A Roman soldier trusted Jesus\' word more than His presence.',
    passageRef: 'Matthew 8:5-13',
    passageTitle: 'The centurion\'s faith',
    category: 'narrative',
    characters: ['Jesus', 'A Roman centurion'],
    verses: [
      { v: 5, text: 'And when Jesus was entered into Capernaum, there came unto him a centurion, beseeching him,' },
      { v: 6, text: 'And saying, Lord, my servant lieth at home sick of the palsy, grievously tormented.' },
      { v: 7, text: 'And Jesus saith unto him, I will come and heal him.' },
      { v: 8, text: 'The centurion answered and said, Lord, I am not worthy that thou shouldest come under my roof: but speak the word only, and my servant shall be healed.' },
      { v: 10, text: 'When Jesus heard it, he marvelled... I have not found so great faith, no, not in Israel.' },
      { v: 13, text: '...Go thy way; and as thou hast believed, so be it done unto thee.' },
    ],
    whatsHappening: 'A Roman officer — a Gentile, a representative of Israel\'s oppressors — comes humbly to Jesus for a sick servant. He understands authority. He doesn\'t need Jesus to come; he trusts Jesus\' word from a distance. Jesus is astonished.',
    aboutGod: 'God values faith above pedigree. He honors humility, not religious credentials. He responds to people who take His Word at face value.',
    aboutJesus: 'Jesus speaks and it is done — over disease, distance, death. His word is enough. He marveled at faith that simply believed Him.',
    background: BG.matthew,
    reflection: [
      'Where are you waiting on a feeling or a sign instead of trusting Jesus\' word?',
      'What "great faith" might look like in your real situation this week?',
      'Whose physical or spiritual healing are you carrying to Jesus today?',
    ],
    prayer: 'Jesus, You only have to speak. I take Your word at face value. Heal what I am holding before You today, in Your way and time.',
    actionStep: 'Pick one promise of Jesus from the Gospels. Write it on a card and read it every time you feel doubt today.',
    quickTakeaway: 'Faith is taking Jesus at His word. Speak it. Believe it. Walk in it.',
  }),

  r({
    id: 'jairus-daughter',
    theme: 'Only believe — even when it\'s "too late"',
    oneLine: '"Be not afraid, only believe" — and a dead girl woke up.',
    passageRef: 'Mark 5:35-43',
    passageTitle: 'Jesus raises Jairus\' daughter',
    category: 'narrative',
    characters: ['Jesus', 'Jairus', 'Peter', 'James', 'John'],
    verses: [
      { v: 35, text: '...there came from the ruler of the synagogue\'s house certain which said, Thy daughter is dead: why troublest thou the Master any further?' },
      { v: 36, text: 'As soon as Jesus heard the word that was spoken, he saith unto the ruler of the synagogue, Be not afraid, only believe.' },
      { v: 39, text: '...Why make ye this ado, and weep? the damsel is not dead, but sleepeth.' },
      { v: 41, text: 'And he took the damsel by the hand, and said unto her, Talitha cumi... Damsel, I say unto thee, arise.' },
      { v: 42, text: 'And straightway the damsel arose, and walked...' },
    ],
    whatsHappening: 'Jairus, a synagogue ruler, begs Jesus to heal his dying daughter. On the way, Jesus stops for another woman — and the news comes: too late, she\'s dead. Jesus says one of His tenderest sentences in all the Gospels: "Be not afraid, only believe." He goes anyway. He takes her hand. She wakes up.',
    aboutGod: 'God\'s "too late" is not our "too late." He honors persistent faith even when circumstances scream the opposite.',
    aboutJesus: 'Jesus calls death "sleep" because He has the power to wake the sleeping. This little resurrection points to the great one — His own — and to the day He raises us.',
    background: BG.mark,
    reflection: [
      'What situation feels "too late" to you right now?',
      'Jesus\' first word to fear was, "Be not afraid, only believe." What might it look like to obey that today?',
      'Where do you need to keep walking with Jesus even when everyone else has stopped hoping?',
    ],
    prayer: 'Jesus, when the noise says "too late," help me hear Your "only believe." Take me by the hand today. I trust You.',
    actionStep: 'Write down the situation that feels "too late." Underline it and write next to it: "Be not afraid, only believe."',
    quickTakeaway: '"Too late" is not in Jesus\' vocabulary. Keep walking with Him.',
  }),

  r({
    id: 'washing-feet',
    theme: 'Greatness looks like a towel',
    oneLine: 'On His last night, Jesus knelt and washed the feet of His friends.',
    passageRef: 'John 13:3-15',
    passageTitle: 'Jesus washes the disciples\' feet',
    category: 'narrative',
    characters: ['Jesus', 'The Twelve', 'Peter'],
    verses: [
      { v: 3, text: 'Jesus knowing that the Father had given all things into his hands, and that he was come from God, and went to God;' },
      { v: 4, text: 'He riseth from supper, and laid aside his garments; and took a towel, and girded himself.' },
      { v: 5, text: 'After that he poureth water into a bason, and began to wash the disciples\' feet...' },
      { v: 14, text: 'If I then, your Lord and Master, have washed your feet; ye also ought to wash one another\'s feet.' },
      { v: 15, text: 'For I have given you an example, that ye should do as I have done to you.' },
    ],
    whatsHappening: 'It is the Last Supper. Jesus knows the cross is hours away. He also knows Judas will betray Him and Peter will deny Him. With full awareness of His authority and identity, He takes the slave\'s job — washing road-dirty feet of men who will fail Him.',
    aboutGod: 'God\'s greatness shows up as service. Authority in His kingdom kneels.',
    aboutJesus: 'Jesus washed feet on His way to the cross — small service before the great one. He still serves us today as our risen High Priest, and He calls us to follow His example.',
    background: BG.john,
    reflection: [
      'Whose feet — practically — is Jesus asking you to wash this week?',
      'Where do you struggle to be served (like Peter)?',
      'How does Jesus\' security in His identity free Him to serve? What does that show you?',
    ],
    prayer: 'Jesus, You knelt. Help me kneel. Strip the pride out of me. Let me love by serving someone today the way You have served me.',
    actionStep: 'Do one act of hidden service today — something no one will thank you for. Do it as worship.',
    quickTakeaway: 'In Jesus\' kingdom, greatness picks up the towel.',
  }),

  r({
    id: 'upper-room-promise',
    theme: 'Do not let your heart be troubled',
    oneLine: 'Jesus prepared His friends for His absence by promising His presence.',
    passageRef: 'John 14:1-6',
    passageTitle: 'In My Father\'s house',
    category: 'teaching',
    characters: ['Jesus', 'The disciples', 'Thomas'],
    verses: [
      { v: 1, text: 'Let not your heart be troubled: ye believe in God, believe also in me.' },
      { v: 2, text: 'In my Father\'s house are many mansions: if it were not so, I would have told you. I go to prepare a place for you.' },
      { v: 3, text: 'And if I go and prepare a place for you, I will come again, and receive you unto myself; that where I am, there ye may be also.' },
      { v: 6, text: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.' },
    ],
    whatsHappening: 'In the Upper Room hours before the cross, Jesus prepares His disciples for what feels like the end. He gives them a promise: I\'m coming back, I\'m preparing a place, and in the meantime — trust Me.',
    aboutGod: 'God is preparing a future for His people. The Father\'s house has room. Eternity is real and personal.',
    aboutJesus: 'Jesus does not point us to a path; He says, "I am the way." Salvation is a Person. The cross opens the door. The resurrection guarantees the welcome.',
    background: BG.john,
    reflection: [
      'What troubled thought needs to hear, "ye believe in God, believe also in me" today?',
      'What does it change to know Jesus is actively preparing a place for you?',
      'How does "I am the way" simplify your faith?',
    ],
    prayer: 'Jesus, my heart is troubled about ___. I believe in You. Settle me with Your promise: You\'re preparing a place, and You\'re coming back. You are the way.',
    actionStep: 'Read John 14:1-6 every morning this week. End with one specific worry surrendered to Jesus.',
    quickTakeaway: 'Trust Jesus. He is the way, and He is preparing your place.',
  }),

  r({
    id: 'road-emmaus',
    theme: 'Jesus walks with us before we recognize Him',
    oneLine: 'Two heartbroken disciples found that the risen Jesus had been with them the whole way.',
    passageRef: 'Luke 24:13-32',
    passageTitle: 'On the road to Emmaus',
    category: 'narrative',
    characters: ['Cleopas', 'Another disciple', 'The risen Jesus'],
    verses: [
      { v: 15, text: 'And it came to pass, that, while they communed together and reasoned, Jesus himself drew near, and went with them.' },
      { v: 16, text: 'But their eyes were holden that they should not know him.' },
      { v: 25, text: 'Then he said unto them, O fools, and slow of heart to believe all that the prophets have spoken:' },
      { v: 27, text: 'And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself.' },
      { v: 31, text: 'And their eyes were opened, and they knew him; and he vanished out of their sight.' },
      { v: 32, text: '...Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?' },
    ],
    whatsHappening: 'On resurrection Sunday, two disappointed disciples walk home talking about how it all went wrong. The risen Jesus joins them, hidden. He walks them through the whole Bible — showing how every page pointed to Him. They invite Him in. He breaks bread. Their eyes open.',
    aboutGod: 'God meets us in our disappointment and walks at our pace. He opens the Scriptures to people whose hearts are honest.',
    aboutJesus: 'Jesus is the key to every page of the Bible — "in all the scriptures the things concerning himself." Reading without Him is reading half the story.',
    background: BG.luke,
    reflection: [
      'Where does your "we had hoped" sentence go right now?',
      'How does it change you to know the risen Jesus is walking with you in your disappointment?',
      'When was the last time the Scriptures made your heart burn?',
    ],
    prayer: 'Risen Jesus, walk with me on my road. Open the Scriptures to me. Make my heart burn for You again.',
    actionStep: 'Read one Old Testament passage today asking, "How does this point to Jesus?" Write down what you see.',
    quickTakeaway: 'The risen Jesus is on your road. He opens Scripture. He stays for dinner.',
  }),

  // ============ ACTS ============
  r({
    id: 'stephen-martyr',
    theme: 'Faithful to the end — like Jesus',
    oneLine: 'Even while being stoned, Stephen looked like Jesus.',
    passageRef: 'Acts 7:54-60',
    passageTitle: 'The death of Stephen',
    category: 'narrative',
    characters: ['Stephen', 'The Sanhedrin', 'Saul of Tarsus'],
    verses: [
      { v: 55, text: 'But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God,' },
      { v: 56, text: 'And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God.' },
      { v: 59, text: 'And they stoned Stephen, calling upon God, and saying, Lord Jesus, receive my spirit.' },
      { v: 60, text: 'And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge. And when he had said this, he fell asleep.' },
    ],
    whatsHappening: 'Stephen — the church\'s first deacon — preaches a sermon that traces God\'s faithfulness through Israel and ends with a confrontation. The crowd rages and stones him. As he dies, he sees Jesus, commits his spirit, and forgives. A young Pharisee named Saul watches the coats.',
    aboutGod: 'God stands when His servants stand. The seeds of Saul\'s later conversion are planted in Stephen\'s forgiveness.',
    aboutJesus: 'Stephen\'s last words echo Jesus\' on the cross: "receive my spirit" and "lay not this sin to their charge." When we walk with Jesus, we start to die like Him too — full of faith and forgiveness.',
    background: BG.acts,
    reflection: [
      'Where is faithfulness costing you something right now?',
      'How does it strengthen you to know Jesus is standing — not just sitting — when His people suffer?',
      'Who do you need to forgive that no one would blame you for not forgiving?',
    ],
    prayer: 'Jesus, make me faithful where I am. Fill me with Your Spirit so my life — even my hardest moments — looks like Yours.',
    actionStep: 'Pray for one person who has hurt you today. Use Stephen\'s words: "Lord, lay not this sin to their charge."',
    quickTakeaway: 'The Christian life — and death — looks like Jesus. Stand up. Forgive. Trust.',
  }),

  r({
    id: 'philip-ethiopian',
    theme: 'God positions us for one conversation',
    oneLine: 'Philip ran beside a chariot — and a kingdom was opened.',
    passageRef: 'Acts 8:26-38',
    passageTitle: 'Philip and the Ethiopian',
    category: 'narrative',
    characters: ['Philip', 'An Ethiopian official'],
    verses: [
      { v: 27, text: '...behold, a man of Ethiopia, an eunuch of great authority under Candace queen of the Ethiopians... had come to Jerusalem for to worship,' },
      { v: 29, text: 'Then the Spirit said unto Philip, Go near, and join thyself to this chariot.' },
      { v: 31, text: 'And he said, How can I, except some man should guide me? And he desired Philip that he would come up and sit with him.' },
      { v: 35, text: 'Then Philip opened his mouth, and began at the same scripture, and preached unto him Jesus.' },
      { v: 38, text: '...and they went down both into the water, both Philip and the eunuch; and he baptized him.' },
    ],
    whatsHappening: 'Philip is sent into a desert. He sees a foreigner reading Isaiah 53. The Spirit says, "Go." He runs, asks a question, gets invited up, and shares Jesus. The official believes and is baptized on the spot.',
    aboutGod: 'God positions His people for specific conversations. He cares about every seeker — even one foreigner in a chariot in a desert.',
    aboutJesus: 'Philip "began at the same scripture, and preached unto him Jesus." The whole Bible — including Isaiah 53 — leads to Christ. Sharing the gospel is sharing Him.',
    background: BG.acts,
    reflection: [
      'Who in your life is reading, asking, or searching right now?',
      'What\'s your honest response when the Spirit nudges you to "go near"?',
      'How comfortable are you opening the Scriptures and talking about Jesus with someone?',
    ],
    prayer: 'Spirit, position me. Open my eyes to the person You\'re sending me to. Open my mouth to speak about Jesus simply and clearly.',
    actionStep: 'Ask God to show you one person to "go near" this week. When He does, ask them one honest question about their life.',
    quickTakeaway: 'God positions you for conversations. Listen. Go. Speak Jesus.',
  }),

  r({
    id: 'peter-cornelius',
    theme: 'God shows no partiality',
    oneLine: 'When Peter walked into a Gentile\'s house, the church grew up.',
    passageRef: 'Acts 10:34-43',
    passageTitle: 'Peter and Cornelius',
    category: 'narrative',
    characters: ['Peter', 'Cornelius'],
    verses: [
      { v: 34, text: 'Then Peter opened his mouth, and said, Of a truth I perceive that God is no respecter of persons:' },
      { v: 35, text: 'But in every nation he that feareth him, and worketh righteousness, is accepted with him.' },
      { v: 36, text: 'The word which God sent unto the children of Israel, preaching peace by Jesus Christ: (he is Lord of all:)' },
      { v: 43, text: 'To him give all the prophets witness, that through his name whosoever believeth in him shall receive remission of sins.' },
    ],
    whatsHappening: 'Cornelius — a Roman officer — sees an angel and is told to send for Peter. Peter sees a vision teaching him not to call any person "unclean." When Peter walks into the Gentile\'s house and preaches Jesus, the Spirit falls on everyone listening. The church will never be the same.',
    aboutGod: 'God plays no favorites. He invites every nation, every background, every person to come to Jesus.',
    aboutJesus: 'Jesus is "Lord of all" — not just one nation, one type. Through His name, whoever believes is forgiven. The "whoever" is the whole point.',
    background: BG.acts,
    reflection: [
      'Who do you secretly assume is "out of reach" of the gospel?',
      'Where might God be expanding your category of "us"?',
      'Who is your Cornelius — someone you\'d normally not cross the room for?',
    ],
    prayer: 'Lord Jesus, You are Lord of all — not just people like me. Tear down the walls in my heart. Send me to the people I would not naturally choose.',
    actionStep: 'Pray today for one person or group you usually ignore or write off. Ask God how to love them like Jesus does.',
    quickTakeaway: 'God plays no favorites. Neither should we.',
  }),

  r({
    id: 'paul-conversion',
    theme: 'No one is too far gone for Jesus',
    oneLine: 'The man hunting Christians met the risen Jesus on the road.',
    passageRef: 'Acts 9:1-9',
    passageTitle: 'Saul meets Jesus',
    category: 'narrative',
    characters: ['Saul', 'The risen Jesus', 'Ananias'],
    verses: [
      { v: 1, text: 'And Saul, yet breathing out threatenings and slaughter against the disciples of the Lord, went unto the high priest,' },
      { v: 3, text: '...as he journeyed, he came near Damascus: and suddenly there shined round about him a light from heaven:' },
      { v: 4, text: 'And he fell to the earth, and heard a voice saying unto him, Saul, Saul, why persecutest thou me?' },
      { v: 5, text: 'And he said, Who art thou, Lord? And the Lord said, I am Jesus whom thou persecutest...' },
      { v: 6, text: 'And he trembling and astonished said, Lord, what wilt thou have me to do?' },
    ],
    whatsHappening: 'Saul is the most dangerous enemy of the church. On his way to arrest Christians, the risen Jesus stops him in the road. In a moment, Saul\'s entire life is reordered. The persecutor becomes the apostle Paul.',
    aboutGod: 'God can interrupt anyone. He shows His glory in saving the people no one expects — and using them to build His church.',
    aboutJesus: 'Jesus calls persecution of His church persecution of Himself — that\'s how united He is with His people. He doesn\'t reform Saul; He raises him. That\'s the only way grace works.',
    background: BG.acts,
    reflection: [
      'Who in your life have you written off as "too far gone"?',
      'What might God be interrupting in your life right now?',
      'Saul\'s second question was, "Lord, what wilt thou have me to do?" What\'s yours?',
    ],
    prayer: 'Jesus, save the Saul I have written off. Interrupt me wherever I\'m running. I ask Saul\'s question: what will You have me to do?',
    actionStep: 'Write down the name of one person you\'ve given up praying for. Start praying for them again — daily for the next 30 days.',
    quickTakeaway: 'Jesus saves the people we wouldn\'t. Keep praying.',
  }),

  r({
    id: 'paul-missionary',
    theme: 'The gospel sent to ordinary places by ordinary people',
    oneLine: 'The first missionaries were commissioned by a praying, fasting church.',
    passageRef: 'Acts 13:1-5',
    passageTitle: 'Paul and Barnabas sent out',
    category: 'narrative',
    characters: ['Paul', 'Barnabas', 'The church at Antioch'],
    verses: [
      { v: 2, text: 'As they ministered to the Lord, and fasted, the Holy Ghost said, Separate me Barnabas and Saul for the work whereunto I have called them.' },
      { v: 3, text: 'And when they had fasted and prayed, and laid their hands on them, they sent them away.' },
      { v: 4, text: 'So they, being sent forth by the Holy Ghost, departed unto Seleucia; and from thence they sailed unto Cyprus.' },
      { v: 5, text: 'And when they were at Salamis, they preached the word of God in the synagogues of the Jews...' },
    ],
    whatsHappening: 'The diverse, growing church at Antioch is worshiping and fasting when the Spirit speaks: send Paul and Barnabas. The church confirms, prays, lays on hands, and sends. From this one moment, the gospel begins moving through the Roman world.',
    aboutGod: 'God sends. Mission is His idea, not a human program. He calls ordinary believers and uses local churches to launch them.',
    aboutJesus: 'The Great Commission Jesus gave (Matthew 28) plays out here in real time. He builds His church by sending His people.',
    background: BG.acts,
    reflection: [
      'Are you part of a "sending" church — a community that releases people on mission?',
      'Where might God be sending you (your job, neighborhood, family) as a witness?',
      'Who could you be commissioning, encouraging, or sending today?',
    ],
    prayer: 'Lord of the harvest, You are still sending. Send me where You want me. And use me to send and support others on mission.',
    actionStep: 'Identify your "Antioch" — your local church or faith community. Show up this week ready to serve, give, or be sent.',
    quickTakeaway: 'Jesus sends ordinary people on extraordinary missions. Yes, you.',
  }),

  // ============ CHRISTIAN LIVING ============
  r({
    id: 'spiritual-gifts',
    theme: 'Every believer has been gifted to build others up',
    oneLine: 'The Spirit hands out gifts so the whole church can grow.',
    passageRef: '1 Corinthians 12:4-11',
    passageTitle: 'Gifts of the Spirit',
    category: 'letter',
    characters: ['Paul', 'The church at Corinth'],
    verses: [
      { v: 4, text: 'Now there are diversities of gifts, but the same Spirit.' },
      { v: 5, text: 'And there are differences of administrations, but the same Lord.' },
      { v: 7, text: 'But the manifestation of the Spirit is given to every man to profit withal.' },
      { v: 11, text: 'But all these worketh that one and the selfsame Spirit, dividing to every man severally as he will.' },
    ],
    whatsHappening: 'The Corinthian church is divided over showy gifts and ignored ones. Paul corrects them: every gift comes from the same Spirit, from the same Lord, for the same purpose — to build the body.',
    aboutGod: 'God is generous. He gifts every believer for the good of others. No Christian is gift-less. No gift is purposeless.',
    aboutJesus: 'These gifts come from Christ, the head of the church (Ephesians 4:7-12). Using your gift is following Jesus.',
    background: BG.paul1Cor,
    reflection: [
      'What has the Spirit consistently used you to do for others?',
      'Where might you be hiding or downplaying a gift?',
      'Who in your church could you encourage in their gifting this week?',
    ],
    prayer: 'Holy Spirit, You have gifted me on purpose. Show me how to use what You\'ve given for Jesus and His people.',
    actionStep: 'Ask two people who know you well: "Where do you see me build others up?" Take their answers seriously.',
    quickTakeaway: 'You are gifted. Use it for the body. That is following Jesus.',
  }),

  r({
    id: 'fruit-of-spirit',
    theme: 'The Spirit grows Christlike character in us',
    oneLine: 'Fruit is grown, not faked.',
    passageRef: 'Galatians 5:16-25',
    passageTitle: 'Walking by the Spirit',
    category: 'letter',
    characters: ['Paul', 'The Galatian churches'],
    verses: [
      { v: 16, text: 'This I say then, Walk in the Spirit, and ye shall not fulfil the lust of the flesh.' },
      { v: 22, text: 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,' },
      { v: 23, text: 'Meekness, temperance: against such there is no law.' },
      { v: 24, text: 'And they that are Christ\'s have crucified the flesh with the affections and lusts.' },
      { v: 25, text: 'If we live in the Spirit, let us also walk in the Spirit.' },
    ],
    whatsHappening: 'The Galatians are tempted to grow Christian character through rules. Paul shows the better way: walk by the Spirit and let Him grow the fruit. Character is not legislated — it\'s cultivated.',
    aboutGod: 'God\'s Spirit is the gardener. He grows in us what no rule could produce. The fruit of His work looks like Jesus.',
    aboutJesus: 'Read the list again — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control. That\'s a portrait of Jesus. The Spirit makes us look like Him over time.',
    background: BG.paulGal,
    reflection: [
      'Which fruit does God seem to be growing in you right now?',
      'Which one feels most lacking?',
      'Where are you trying to force fruit instead of walking with the Spirit?',
    ],
    prayer: 'Holy Spirit, I cannot manufacture Christlike character. Grow Your fruit in me. Make me look more like Jesus this year than last.',
    actionStep: 'Pick one fruit (love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control). Ask God to grow it in you this month — and watch.',
    quickTakeaway: 'You can\'t fake fruit. Walk with the Spirit. He grows it.',
  }),

  r({
    id: 'unity-john17',
    theme: 'Jesus prayed for our unity',
    oneLine: 'On His last night, Jesus prayed that we would be one.',
    passageRef: 'John 17:20-23',
    passageTitle: 'Jesus prays for His church',
    category: 'narrative',
    characters: ['Jesus', 'The Father'],
    verses: [
      { v: 20, text: 'Neither pray I for these alone, but for them also which shall believe on me through their word;' },
      { v: 21, text: 'That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me.' },
      { v: 22, text: 'And the glory which thou gavest me I have given them; that they may be one, even as we are one:' },
      { v: 23, text: 'I in them, and thou in me, that they may be made perfect in one; and that the world may know that thou hast sent me, and hast loved them, as thou hast loved me.' },
    ],
    whatsHappening: 'In John 17, Jesus prays out loud so His disciples hear. He prays specifically for future believers — that includes you. His one big request: that we would be one, so the world would believe.',
    aboutGod: 'God is one in three persons. The unity He calls us to mirrors His own. Disunity in the church distorts the picture; unity proclaims the gospel.',
    aboutJesus: 'Jesus\' love for us flows from the Father\'s love for Him (v. 23). We don\'t love at the bottom of the chain — we love from the top. That\'s why our unity matters.',
    background: BG.john,
    reflection: [
      'Where is your unity with other believers being tested right now?',
      'How does it land that Jesus prayed for you the night before He died?',
      'What\'s one specific step toward unity you can take this week?',
    ],
    prayer: 'Jesus, You prayed for me to be one with Your people. Forgive my pettiness. Make me a peacemaker. Use my church\'s unity to show the world who You are.',
    actionStep: 'Reach out to a believer you\'ve drifted from. Apologize, reconnect, or just bless them. Unity starts with one step.',
    quickTakeaway: 'Our unity is Jesus\' prayer. Live like it matters — because it does.',
  }),

  r({
    id: 'perseverance-james',
    theme: 'Trials produce something God values',
    oneLine: 'Joy in hard things sounds wrong — until you see what God is making.',
    passageRef: 'James 1:2-12',
    passageTitle: 'Count it all joy',
    category: 'letter',
    characters: ['James', 'Scattered believers'],
    verses: [
      { v: 2, text: 'My brethren, count it all joy when ye fall into divers temptations;' },
      { v: 3, text: 'Knowing this, that the trying of your faith worketh patience.' },
      { v: 4, text: 'But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.' },
      { v: 5, text: 'If any of you lack wisdom, let him ask of God... and it shall be given him.' },
      { v: 12, text: 'Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life...' },
    ],
    whatsHappening: 'James writes to scattered, suffering Christians. He doesn\'t soften the hardship. Instead he reframes it — trials are how endurance grows, and endurance is how we mature. And when we lack wisdom for it, we ask.',
    aboutGod: 'God uses what hurts. He doesn\'t waste pressure. He gives wisdom generously to those who ask.',
    aboutJesus: 'Jesus "endured the cross, despising the shame" (Hebrews 12:2). He is both our example and our strength when we feel like we cannot keep going.',
    background: BG.james,
    reflection: [
      'What trial are you currently in?',
      'What might God be growing in you through it — that He couldn\'t grow another way?',
      'What wisdom do you need to ask Him for, today, by name?',
    ],
    prayer: 'Father, I don\'t love this trial. But I trust You. Make me steady. Give me wisdom for the next decision. I want what Jesus is growing in me.',
    actionStep: 'Write down your current trial. Underneath it write, "God is growing ___ in me." Ask Him to fill in the blank.',
    quickTakeaway: 'God is not wasting your hard season. He is growing something only this can grow.',
  }),

  r({
    id: 'faithfulness-talents',
    theme: 'Be faithful with what you actually have',
    oneLine: 'The Master cares more about your faithfulness than your portfolio.',
    passageRef: 'Luke 16:10-13',
    passageTitle: 'Faithful in little',
    category: 'teaching',
    characters: ['Jesus', 'The disciples'],
    verses: [
      { v: 10, text: 'He that is faithful in that which is least is faithful also in much: and he that is unjust in the least is unjust also in much.' },
      { v: 11, text: 'If therefore ye have not been faithful in the unrighteous mammon, who will commit to your trust the true riches?' },
      { v: 13, text: 'No servant can serve two masters... Ye cannot serve God and mammon.' },
    ],
    whatsHappening: 'Jesus teaches that small faithfulness matters. The way we handle money, time, and small responsibilities reveals what we\'d do with bigger ones. He warns: you have one Master.',
    aboutGod: 'God notices small faithfulness. He entrusts more to those who steward little well. He is patient — and serious — about whether He is truly our Master.',
    aboutJesus: 'Jesus is the perfectly faithful Son. He was faithful in obscurity for 30 years before three years of public ministry. He calls us to His pattern: faithful in small, faithful in much.',
    background: BG.luke,
    reflection: [
      'Where have you been treating something "small" as if it didn\'t matter to God?',
      'What is the next faithful step in front of you today?',
      'Where are you trying to serve two masters?',
    ],
    prayer: 'Jesus, I want to be faithful — not famous. Help me be faithful with the small thing in front of me today, and to keep You as my one Master.',
    actionStep: 'Pick one small responsibility you\'ve been half-doing. Do it fully today as worship to Jesus.',
    quickTakeaway: 'Small faithfulness is not small to God. Do the next right thing.',
  }),
];
