
-- Insert passage levels for all passages that are missing content
-- This ensures every passage has content for at least the adult level

-- Saved by Grace - Ephesians 2:8-9
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('053b22db-d551-4abf-8824-270583af6675', 'picture', 'God gives us a special gift - He loves us so much! We don''t have to earn His love. It''s free, like a birthday present!', 'For by grace are ye saved through faith.', '["What is the best gift you ever got?", "How does it feel to know God loves you?", "What can you say to thank God?"]', 'Draw a picture of a gift box with God''s love inside it.', 'Thank you God for loving me so much. You gave me the best gift ever!'),
('053b22db-d551-4abf-8824-270583af6675', 'early_reader', 'God saves us because He loves us, not because we did anything special. It''s called grace - getting something wonderful we didn''t earn. Faith means trusting God''s gift!', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.', '["What is grace?", "Why can''t we earn our way to heaven?", "How do we accept God''s gift?"]', 'Make a thank-you card for God for His gift of grace.', 'Dear God, thank You for saving me. Help me trust You more each day.'),
('053b22db-d551-4abf-8824-270583af6675', 'intermediate', 'Salvation is God''s gift to us through grace. We can''t earn it by being good or doing good works - it comes through faith in Jesus. This takes away any reason to brag because it''s all from God!', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.', '["What''s the difference between grace and works?", "Why would boasting be wrong?", "How does knowing salvation is a gift change how you live?"]', 'Write about a time someone gave you something you didn''t deserve.', 'Lord, help me remember that salvation is Your gift. Keep me humble and grateful.'),
('053b22db-d551-4abf-8824-270583af6675', 'advanced', 'Paul explains the core of the Gospel: salvation comes by grace through faith, not by human effort. This revolutionary truth removes all grounds for self-righteousness. We are saved to do good works, not saved by good works.', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.', '["How does grace differ from religion based on works?", "What role do good works play after salvation?", "How does understanding grace affect your daily life?"]', 'Journal about areas where you''ve tried to earn God''s favor instead of resting in grace.', 'Father, thank You for the gift I could never earn. Help me live from grace, not for grace.'),
('053b22db-d551-4abf-8824-270583af6675', 'young_adult', 'This passage is foundational to Christian theology. Grace (unmerited favor) and faith (trusting belief) work together in salvation. The explicit denial of works-based salvation addresses a universal human tendency toward self-justification.', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.', '["How does grace challenge cultural narratives about earning success?", "What''s the relationship between faith and works in James?", "How do you explain grace to non-believers?"]', 'Study the contrast between grace and law in Galatians 3.', 'God, let the reality of grace transform how I see myself and others.'),
('053b22db-d551-4abf-8824-270583af6675', 'adult', 'Ephesians 2:8-9 presents the Protestant understanding of salvation sola gratia (by grace alone) through sola fide (faith alone). The passage emphasizes God''s initiative in salvation, human inability to self-save, and the exclusion of boasting in any human contribution to redemption.', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.', '["How do these verses inform your understanding of human depravity?", "What is the relationship between Ephesians 2:8-9 and 2:10?", "How should grace shape community life?"]', 'Compare this passage with Romans 3:21-26 and Titus 3:4-7.', 'Gracious God, I receive Your gift with gratitude. May I extend this same grace to others.'),
('053b22db-d551-4abf-8824-270583af6675', 'scholarly', 'The aorist passive participle "σεσῳσμένοι" (having been saved) indicates a completed action with present effects. The phrase "οὐκ ἐξ ὑμῶν" negates human origin of salvation. Paul''s use of "δῶρον" (gift) emphasizes the gratuitous nature of salvation, while "ἵνα μή τις καυχήσηται" provides the teleological purpose.', 'τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως', '["How does the perfect tense participle affect interpretation?", "What is the antecedent of τοῦτο?", "How does this passage interact with Jewish soteriology?"]', 'Exegete this passage using the Greek text and compare various translation approaches.', 'Sovereign Lord, deepen my understanding of Your redemptive work in Christ.');

-- All Things Work Together - Romans 8:28
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('66236531-6e40-42ff-a8e8-fef1267deed8', 'picture', 'God takes everything - even sad things - and makes them into something good for people who love Him!', 'All things work together for good.', '["Can you think of a bad day that ended up okay?", "Who loves you and takes care of you?", "How do you know God loves you?"]', 'Draw before/after pictures showing something bad becoming good.', 'Thank you God for making good things happen, even when I''m sad.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'early_reader', 'God promises that He uses everything in our lives for good - even the hard stuff! This is for people who love God and follow His plan.', 'And we know that all things work together for good to them that love God.', '["What does it mean for things to work together?", "How can something bad become good?", "What shows you love God?"]', 'Make a puzzle showing how different pieces come together.', 'God, help me trust You when things are hard. I know You have a good plan.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'intermediate', 'Paul gives believers incredible hope: God is working behind the scenes in every situation. He doesn''t promise easy lives, but He promises purpose in everything for those who love Him and are called according to His purpose.', 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', '["What''s the difference between everything being good and everything working for good?", "Who is this promise for?", "How does this help during tough times?"]', 'Write about a difficult time that later helped you grow.', 'Father, I trust that You''re working even when I can''t see it. Give me patience.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'advanced', 'Romans 8:28 is a cornerstone of Christian hope. The "good" isn''t necessarily comfort or success, but conformity to Christ (v.29). This promise is conditional - for those who love God and are called. It''s about God''s sovereign orchestration of circumstances.', 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', '["How does context (v.29-30) define ''good''?", "Does this mean bad things are good?", "How do you hold this truth during tragedy?"]', 'Study Joseph''s story in Genesis 50:20 as an example of this principle.', 'Lord, shape me into Christ''s image through every circumstance I face.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'young_adult', 'This verse must be understood in context. The "good" God works toward is Christlikeness (v.29), not material prosperity. Paul writes to suffering believers, assuring them of divine purpose. The verse doesn''t explain evil but affirms God''s sovereignty over it.', 'And we know that all things work together for good to them that love God.', '["How do you share this verse sensitively with someone grieving?", "What''s the relationship between God''s sovereignty and human freedom?", "How does this shape your response to suffering?"]', 'Read Romans 8:18-39 for the full context of suffering and hope.', 'God, help me trust Your purposes when life doesn''t make sense.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'adult', 'Romans 8:28 sits within Paul''s discussion of present suffering and future glory. The Greek συνεργεῖ suggests God''s active cooperation with circumstances. This isn''t fatalism but faith in divine providence. The "good" is defined by v.29: conformity to Christ''s image.', 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', '["How does the golden chain of salvation (v.29-30) relate to this promise?", "What are the dangers of misapplying this verse?", "How does corporate calling affect interpretation?"]', 'Compare with similar themes in Genesis 50:20, Jeremiah 29:11, and James 1:2-4.', 'Sovereign Father, I rest in Your perfect orchestration of my life for Your glory.'),
('66236531-6e40-42ff-a8e8-fef1267deed8', 'scholarly', 'The textual variant between συνεργεῖ (works together) with or without ὁ θεός as subject affects interpretation. The πάντα could be nominative (all things work) or accusative (He works all things). The προθεσιν (purpose) connects to divine election theology developed in 9-11.', 'οἴδαμεν δὲ ὅτι τοῖς ἀγαπῶσιν τὸν θεὸν πάντα συνεργεῖ εἰς ἀγαθόν', '["How do textual variants affect interpretation?", "What is the relationship to theodicy?", "How does this connect to the new perspective on Paul?"]', 'Analyze the chiastic structure of Romans 8:28-30.', 'Lord, may scholarly study deepen worship of Your sovereign grace.');

-- Trust in the Lord - Proverbs 3:5-6
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'picture', 'Trust God with your whole heart! He knows the best way to go, even better than we do!', 'Trust in the Lord with all thine heart.', '["Who do you trust?", "Why should we trust God?", "How can you show you trust God?"]', 'Draw yourself holding God''s hand while He shows you the way.', 'God, help me trust You. You know what''s best for me!'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'early_reader', 'God wants us to trust Him completely, not just rely on what we think we know. When we follow Him in everything, He shows us the right path to take.', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', '["What does it mean to trust with all your heart?", "Why shouldn''t we just trust ourselves?", "How does God show us the way?"]', 'Make a road sign that says "Trust God" and decorate it.', 'Dear Lord, help me trust You more than my own ideas. Show me Your way.'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'intermediate', 'Solomon teaches that wisdom begins with total trust in God, not self-reliance. "All your heart" means complete surrender. When we acknowledge God in every decision, He guides our paths - maybe not always where we expect, but where we need to go.', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', '["What''s the difference between trusting and understanding?", "What does acknowledging God in all ways look like?", "When is it hardest to trust God?"]', 'Keep a trust journal for a week, noting when you relied on God vs. yourself.', 'Father, I confess I often lean on my own understanding. Teach me to trust You fully.'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'advanced', 'This wisdom teaching contrasts faith-based living with autonomous reasoning. The heart (לֵב) represents the whole person. "Lean not" doesn''t forbid thinking but warns against self-sufficient reasoning apart from God. Divine direction comes through acknowledging God''s lordship in every area.', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', '["How do you balance using wisdom and trusting God?", "What areas of life are hardest to surrender?", "How has God directed your path unexpectedly?"]', 'Identify three decisions you''re facing and practice acknowledging God in each.', 'Lord, I surrender my plans and understanding to Your perfect wisdom.'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'young_adult', 'Proverbs 3:5-6 addresses the tension between human responsibility and divine sovereignty. Trust (בָּטַח) involves confident reliance. The warning against self-understanding isn''t anti-intellectual but anti-autonomous. "Direct" (יְיַשֵּׁר) means to make straight or smooth.', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', '["How does this passage inform decision-making?", "What''s the relationship between faith and reason?", "How do you discern God''s direction?"]', 'Study how biblical figures like Abraham and David trusted God despite circumstances.', 'God, align my heart and mind with Your will in every decision I make.'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'adult', 'This passage presents the epistemological foundation of wisdom literature: true knowledge begins with trust in Yahweh. The contrast between בָּטַח (trust) and שָׁעַן (lean) shows the difference between confident faith and precarious self-reliance. Divine guidance (יְיַשֵּׁר) implies both removal of obstacles and moral straightening.', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', '["How does this passage relate to the fear of the Lord in Proverbs 1:7?", "What is the Hebrew understanding of heart?", "How does community wisdom relate to individual trust?"]', 'Compare with Proverbs 16:3, 16:9, and 20:24 for a fuller picture of divine guidance.', 'Yahweh, I trust Your covenant faithfulness to guide me in righteousness.'),
('88ec26a9-1af4-4499-a374-5fe5e977903f', 'scholarly', 'The imperative בְּטַח (trust) governs the passage. The prepositional phrase בְּכָל־לִבְּךָ emphasizes totality. The negative אַל־תִּשָּׁעֵן with עַל־בִּינָתֶךָ creates antithetical parallelism. The hiphil יְיַשֵּׁר promises divine causation in making paths straight (אֹרְחֹתֶיךָ).', 'בְּטַח אֶל־יְהוָה בְּכָל־לִבֶּךָ וְאֶל־בִּינָתְךָ אַל־תִּשָּׁעֵן', '["How does this fit within the structure of Proverbs 3?", "What ANE parallels exist for this wisdom teaching?", "How do LXX and MT differ?"]', 'Analyze the verbal roots and their semantic ranges in this passage.', 'Lord of wisdom, grant understanding as I study Your eternal Word.');

-- They Shall Mount Up With Wings - Isaiah 40:31
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'picture', 'When we wait for God, He makes us strong like eagles that fly high in the sky!', 'They shall mount up with wings as eagles.', '["Have you seen an eagle fly?", "What does it feel like to be tired?", "How can God make you strong?"]', 'Make eagle wings out of paper and pretend to fly!', 'God, when I''m tired, help me be strong like an eagle!'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'early_reader', 'God gives special strength to people who wait for Him. They can soar like eagles, run without getting worn out, and walk without being tired. God''s power never runs out!', 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles.', '["What does waiting on God mean?", "Why does God use an eagle as an example?", "When do you need God''s strength?"]', 'Draw an eagle soaring and write the verse on it.', 'Lord, teach me to wait for You. Fill me with Your eagle-strength!'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'intermediate', 'Isaiah promises that those who wait on (hope in) the Lord will have their strength renewed. The eagle imagery shows how God enables us to rise above our circumstances. The progression from soaring to running to walking shows strength for every season of life.', 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', '["Why does waiting come before strength?", "What''s the significance of eagles, running, and walking?", "How do you practically wait on God?"]', 'Research how eagles soar on thermal currents without flapping.', 'Father, I wait on You. Renew my strength when I feel like giving up.'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'advanced', 'Written to exhausted exiles, Isaiah 40 contrasts human frailty with God''s inexhaustible power. "Wait" (קָוָה) means to hope with expectant patience. Eagles soar by riding thermals - the image suggests resting in God''s power rather than striving. The downward progression (soar, run, walk) may emphasize that God strengthens ordinary daily faithfulness.', 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', '["How does the context of exile inform this promise?", "What''s the theological significance of the progression?", "How does waiting demonstrate faith?"]', 'Journal about a season of waiting and how God renewed your strength.', 'Everlasting God, I rest in Your unfailing power when my strength fails.'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'young_adult', 'Isaiah 40:31 concludes a chapter that moves from accusation to comfort. The rhetorical questions of v.27-28 address Israel''s complaint that God has forgotten them. The promise assures weary believers that divine strength comes through patient trust, enabling them to transcend circumstances.', 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles.', '["How do you maintain hope during prolonged difficulty?", "What''s the difference between waiting and passivity?", "How does this passage address burnout?"]', 'Study the full context of Isaiah 40 as comfort to exiles.', 'Lord, when I''m tempted to give up, remind me that You never grow weary.'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'adult', 'This climactic promise follows Isaiah''s declaration of God''s incomparability and sovereign power over creation. The qal participle קֹוֵי (those waiting) suggests ongoing, habitual waiting. The hiphil יַחֲלִיפוּ means to exchange or renew - trading human weakness for divine strength.', 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', '["How does this promise function within Isaiah''s theology?", "What is the relationship between waiting and worship?", "How does eagle imagery function elsewhere in Scripture?"]', 'Compare with Exodus 19:4, Deuteronomy 32:11, and Psalm 103:5.', 'Creator God, I exchange my weakness for Your everlasting strength.'),
('6e69d2a7-1b2d-4e7c-97b7-43f4cfe04621', 'scholarly', 'The root קוה (wait/hope) in participial form indicates continuous action. The hiphil יַחֲלִיפוּ כֹחַ could mean "exchange strength" or "renew strength." The אֶבֶר (pinion/wing) and נֶשֶׁר (eagle/vulture) imagery connects to Exodus motifs. The descending parallelism (soar→run→walk) may be intentional climax or anti-climax.', 'וְקֹוֵי יְהוָה יַחֲלִיפוּ כֹחַ יַעֲלוּ אֵבֶר כַּנְּשָׁרִים', '["What is the semantic range of יַחֲלִיפוּ?", "How does Deutero-Isaiah use nature imagery?", "What is the function of rhetorical questions in the context?"]', 'Analyze the structure of Isaiah 40 and the placement of this conclusion.', 'Eternal One, grant wisdom as I study Your comforting Word to exiles.');

-- Plans to Prosper You - Jeremiah 29:11
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'picture', 'God has good plans for you! He wants to give you hope and a happy future!', 'I know the plans I have for you.', '["Do you make plans?", "How does it feel to know God has good plans for you?", "What makes you hopeful?"]', 'Draw a picture of something good you hope for in the future.', 'Thank you God for having good plans for me!'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'early_reader', 'God told His people: I have wonderful plans for you! Not plans to hurt you, but plans to help you and give you hope for the future.', 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', '["What kind of plans does God have?", "Why is it important to have hope?", "How do you know God cares about your future?"]', 'Make a "hope jar" and fill it with things you''re hopeful about.', 'Dear God, thank You for thinking good thoughts about me. Help me trust Your plans.'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'intermediate', 'God spoke these words to Israelites in exile in Babylon. Even in a difficult situation that would last 70 years, God assured them He had good plans for their future. This reminds us that God sees beyond our current struggles.', 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', '["Who was this promise originally for?", "How can hard times be part of God''s good plan?", "What does this teach about waiting for God''s timing?"]', 'Research the Babylonian exile and why this promise mattered so much.', 'Father, even when life is hard, help me trust that You have good plans ahead.'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'advanced', 'This verse is often quoted out of context. It was written to Jewish exiles facing 70 years in Babylon - not a quick fix. The promise is communal (plural "you") and future-oriented. Yet it reveals God''s character: His ultimate intentions are restorative, not destructive.', 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', '["How does context change your understanding of this verse?", "What''s the difference between individual and corporate promises?", "How do you hold hope during long-term difficulties?"]', 'Read Jeremiah 29:1-14 for the full context of this famous verse.', 'Lord, teach me to hope in Your long-term faithfulness, not quick solutions.'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'young_adult', 'Jeremiah wrote to counter false prophets promising quick deliverance. God''s actual plan? Settle in Babylon, seek its welfare, and wait 70 years. The "hope and future" came through patient faithfulness, not escape. This challenges prosperity gospel interpretations.', 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', '["How has this verse been misapplied?", "What does seeking the city''s welfare mean for Christians today?", "How do you balance hope and realism?"]', 'Compare the true prophets'' message with the false prophets in Jeremiah 28-29.', 'God of hope, help me trust Your timeline even when it''s longer than I want.'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'adult', 'Jeremiah 29:11 must be read within its literary and historical context. God instructs the exiles to build houses, plant gardens, and pray for Babylon (v.5-7). The "hope and future" (אַחֲרִית וְתִקְוָה) comes after extended faithfulness, not instead of it.', 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', '["How does the letter structure affect interpretation?", "What is the relationship between exile theology and New Testament suffering?", "How should this passage shape prosperity gospel critique?"]', 'Study the concept of exile in both testaments and its spiritual applications.', 'Faithful God, ground my hope in Your character, not in circumstances.'),
('0ee9ef2d-f8b1-4b15-a6ff-2da8bb0205e1', 'scholarly', 'The Hebrew מַחְשָׁבוֹת (thoughts/plans) indicates intentional purpose. The phrase לְשָׁלוֹם וְלֹא לְרָעָה contrasts shalom (wholeness) with ra''ah (evil/disaster). The אַחֲרִית (latter end/future) connects to prophetic eschatology. The LXX reading differs significantly from MT in this chapter.', 'כִּי אָנֹכִי יָדַעְתִּי אֶת־הַמַּחֲשָׁבֹת אֲשֶׁר אָנֹכִי חֹשֵׁב עֲלֵיכֶם', '["How do MT and LXX differ in chapter 29?", "What is the semantic range of שָׁלוֹם?", "How does this passage function in exile theology?"]', 'Compare the Hebrew and Greek texts of Jeremiah 29.', 'Lord of history, deepen my understanding of Your prophetic word.');

-- Continue with remaining passages...
-- Seek First the Kingdom - Matthew 6:33
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'picture', 'Put God first! When we love God most, He takes care of everything we need!', 'Seek ye first the kingdom of God.', '["What does it mean to put something first?", "What do you need?", "How do you show God is first?"]', 'Make a list of things you need and put God at the top!', 'God, help me put You first every day!'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'early_reader', 'Jesus tells us not to worry about food or clothes. Instead, we should focus on God''s kingdom first, and He promises to give us what we need.', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', '["What does seeking God''s kingdom mean?", "What do people often worry about?", "How does this help with worry?"]', 'Draw two pictures: worried about stuff vs. trusting God.', 'Dear Jesus, help me seek You first and not worry about other things.'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'intermediate', 'In the Sermon on the Mount, Jesus addresses anxiety about material needs. His solution isn''t just "don''t worry" but "prioritize differently." When God''s kingdom and righteousness become our primary pursuit, other needs fall into proper perspective.', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', '["What is God''s kingdom?", "What is God''s righteousness?", "How does this change what you worry about?"]', 'Track what you spend most time thinking about this week.', 'Lord, reorder my priorities. Help me seek Your kingdom above everything else.'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'advanced', 'Jesus'' teaching on anxiety (Matt 6:25-34) culminates in this command. The kingdom refers to God''s reign; righteousness refers to right relationship with God and right living. "Added" suggests abundance beyond mere necessity. This is about trust, not passivity.', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', '["How do you actively seek the kingdom?", "What''s the relationship between faith and responsibility?", "How does this address modern consumerism?"]', 'Evaluate your time, money, and energy to see what you''re really seeking first.', 'King Jesus, align my desires with Your kingdom priorities.'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'young_adult', 'This verse summarizes Jesus'' teaching on worry and wealth. The aorist imperative "seek" demands decisive action. Kingdom and righteousness are connected - entering God''s reign involves pursuing His standards. The promise isn''t prosperity but provision.', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', '["How does career ambition relate to seeking first the kingdom?", "What''s the relationship between this verse and the Lord''s Prayer?", "How do you practice this in a consumer culture?"]', 'Study Matthew 6:19-34 as a unit on money, worry, and priorities.', 'God, free me from the tyranny of wanting more. Satisfy me with Your kingdom.'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'adult', 'The verb ζητεῖτε (seek) is present imperative - ongoing pursuit. The βασιλείαν (kingdom) refers to God''s dynamic reign. δικαιοσύνην (righteousness) encompasses both forensic (declared right) and ethical (living right) dimensions. The passive προστεθήσεται implies divine provision.', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', '["How does this relate to realized vs. future eschatology?", "What is the Matthean understanding of righteousness?", "How does this function within the Sermon on the Mount structure?"]', 'Compare with Luke 12:31 and analyze the Matthean additions.', 'Sovereign Lord, may Your kingdom come in and through my life today.'),
('ac51a24a-8327-4cf5-beb7-f42a1cce7bb9', 'scholarly', 'The πρῶτον (first) establishes priority rather than mere sequence. The phrase τὴν βασιλείαν καὶ τὴν δικαιοσύνην αὐτοῦ with single article may indicate hendiadys: "righteous kingdom" or "kingdom-righteousness." The future passive προστεθήσεται is divine passive.', 'ζητεῖτε δὲ πρῶτον τὴν βασιλείαν καὶ τὴν δικαιοσύνην αὐτοῦ', '["How does Matthean righteousness differ from Pauline?", "What is the relationship to Q source material?", "How does this function in Sermon on the Mount ethics?"]', 'Analyze the chiastic structure of Matthew 6:19-34.', 'Father, illuminate Your word as I study the ethics of Jesus.');

-- Be Strong and Courageous - Joshua 1:9
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'picture', 'God says: Be strong and brave! I am always with you wherever you go!', 'Be strong and of a good courage.', '["What makes you scared?", "How does having someone with you help?", "Is God with you right now?"]', 'Make a superhero cape that says "God is with me!"', 'God, thank You for always being with me. Help me be brave!'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'early_reader', 'When Joshua was about to lead Israel into the Promised Land, God told him to be strong and brave. Why? Because God would be with him everywhere he went!', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', '["Who was Joshua?", "Why could Joshua be brave?", "Where does God go with you?"]', 'Make a shield with the verse on it to remind you God is with you.', 'Lord, help me be brave like Joshua because You are always with me.'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'intermediate', 'God commissioned Joshua to lead Israel after Moses died. Three times God told him to be strong and courageous. The reason for courage wasn''t Joshua''s ability but God''s presence. Fear is natural, but God''s presence gives us power to overcome it.', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', '["What was Joshua''s big challenge?", "Why does God repeat this command three times?", "When do you need to remember God is with you?"]', 'Write about a scary situation and how knowing God was present helped (or could help).', 'Father, when fear comes, remind me that You are with me.'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'advanced', 'Joshua 1:9 concludes God''s commissioning of Joshua. The paired commands (be strong/courageous, don''t fear/be dismayed) address both action and emotion. God''s presence is the basis for courage. This pattern of divine commission appears throughout Scripture.', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', '["How does context shape application of this verse?", "What''s the relationship between courage and obedience (v.7-8)?", "How do you apply a specific promise to Joshua generally?"]', 'Study other divine commissions in Scripture (Abraham, Moses, Gideon, Jeremiah).', 'Mighty God, empower me to face challenges with courage rooted in Your presence.'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'young_adult', 'This verse is part of a literary pattern where God commissions leaders. The commands to be strong are tied to obedience to Torah (v.7-8). Joshua''s courage isn''t self-generated motivation but response to God''s promise of presence. The command addresses legitimate fear.', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', '["How is biblical courage different from secular concepts?", "What role does God''s word play in Joshua''s courage?", "How do you develop courage for your calling?"]', 'Identify your biggest fear and write how God''s presence speaks to it.', 'Lord, replace my fear with faith in Your unfailing presence.'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'adult', 'The verbs חֲזַק (be strong) and אֱמָץ (be courageous) appear together frequently in Deuteronomic literature. The negative commands address יָרֵא (fear) and חָתַת (dismay/terror). God''s presence formula echoes the patriarchal promises and anticipates the Immanuel theme.', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', '["How does this verse function in Deuteronomistic theology?", "What is the relationship between divine presence and covenant faithfulness?", "How does this connect to New Testament promises?"]', 'Trace the "I am with you" formula from Genesis through Revelation.', 'Ever-present God, my courage rests in Your covenant faithfulness.'),
('073ca5dd-2be5-4c6c-b788-e63d634246fb', 'scholarly', 'The Hebrew חֲזַק וֶאֱמָץ forms a hendiadys of similar meaning. אַל־תַּעֲרֹץ וְאַל־תֵּחָת pair יָרֵא (fear) with חָתַת (shattered/dismayed). The כִּי clause introduces the ground for commands. The presence formula עִמְּךָ יְהוָה אֱלֹהֶיךָ echoes Deuteronomic theology.', 'חֲזַק וֶאֱמָץ אַל־תַּעֲרֹץ וְאַל־תֵּחָת כִּי עִמְּךָ יְהוָה אֱלֹהֶיךָ בְּכֹל אֲשֶׁר תֵּלֵךְ', '["How does this relate to Deuteronomic History?", "What is the theological significance of the presence formula?", "How does this function in later Jewish and Christian interpretation?"]', 'Compare Joshua 1 with Deuteronomy 31 for intertextual connections.', 'YHWH, grant wisdom as I study Your commissioning word.');

-- Be Still and Know - Psalm 46:10
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'picture', 'God says: Stop and rest! Know that I am God and I am in charge!', 'Be still, and know that I am God.', '["Can you sit very still?", "What does it feel like to be quiet?", "What do you know about God?"]', 'Practice sitting still for one minute thinking about God.', 'God, help me be still and remember You are in charge!'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'early_reader', 'When everything around us is crazy and scary, God says: "Stop. Be quiet. Remember that I am God." He is our safe place and He is in control.', 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.', '["What makes you feel scared or worried?", "What does being still help you do?", "How is God different from everything else?"]', 'Find a quiet spot, close your eyes, and whisper "God is in control" three times.', 'Lord, when I''m scared, help me stop and remember You are God.'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'intermediate', 'Psalm 46 describes chaos - earthquakes, nations raging, kingdoms falling. In the middle of this, God says "Be still." This isn''t just about being quiet; it''s about stopping our striving and recognizing God''s sovereignty over everything.', 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.', '["What kind of chaos is described in Psalm 46?", "What does ''be still'' really mean?", "How do you practice stillness?"]', 'Read all of Psalm 46 and list the chaotic things and the peaceful things.', 'Sovereign God, quiet my anxious heart. Help me rest in Your control.'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'advanced', 'The Hebrew הַרְפּוּ means "cease, let go, relax." It''s a command to stop striving, fighting, worrying. In context, this may be God addressing warring nations or His own people. The declaration "I am God" asserts divine sovereignty over all earthly powers.', 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.', '["What does the Hebrew meaning add to your understanding?", "How does the context of war and chaos inform interpretation?", "Is this primarily comfort or confrontation?"]', 'Practice lectio divina with this verse, spending time in silence after reading.', 'Most High God, I surrender my striving and rest in Your sovereign rule.'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'young_adult', 'This verse is often applied to personal devotional stillness, but the context is cosmic - nations raging, kingdoms tottering. God''s command may be to the nations: "Stop fighting!" Or to His people: "Stop worrying." Either way, divine sovereignty is the basis for peace.', 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.', '["How does context challenge typical applications?", "What''s the relationship between stillness and trust?", "How do you find stillness in a noisy world?"]', 'Study the historical events that may have inspired Psalm 46 (Assyrian crisis?).', 'God, in a world of constant noise, teach me the discipline of stillness before You.'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'adult', 'The verb הַרְפּוּ (hiphil imperative of רָפָה) means to let drop, be slack, cease. The context of nations raging suggests God addressing hostile powers. יְדָע אֲנִי אֱלֹהִים recalls the covenant formula. The Psalm structure (three strophes with selah) builds to this declaration.', 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.', '["How does the Psalm''s structure inform v.10?", "Is this addressed to enemies or Israel?", "What is the theological significance of the refrain ''The Lord of hosts is with us''?"]', 'Compare with Isaiah 37:36-38 for possible historical background.', 'Lord of Hosts, I rest in Your sovereign power over all nations.'),
('8bb2c271-97a9-4b41-9bff-21f0855ed71c', 'scholarly', 'The hiphil imperative הַרְפּוּ from רָפָה means "cause to drop, let alone." The address (to nations or Israel) affects interpretation significantly. The phrase אֱלֹהִים אָנֹכִי echoes the self-identification formula. The Korahite Psalm uses מָחֶסֶה and מָנוֹס imagery from asylum tradition.', 'הַרְפּוּ וּדְעוּ כִּי־אָנֹכִי אֱלֹהִים אָרוּם בַּגּוֹיִם אָרוּם בָּאָרֶץ', '["What is the Sitz im Leben of this Psalm?", "How does the Korahite collection inform interpretation?", "What is the relationship to Zion theology?"]', 'Analyze the strophic structure and the function of the selah markers.', 'Elohim, grant insight into Your holy Word as I study.');

-- Continue with more passages...
-- Love is Patient - 1 Corinthians 13:4-7
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'picture', 'Love is patient and kind. Love doesn''t get jealous or brag. Love is the best!', 'Love is patient, love is kind.', '["What is love?", "How can you be patient?", "How can you be kind?"]', 'Draw hearts and write kind things you can do for others.', 'God, help me love others by being patient and kind!'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'early_reader', 'Paul describes what real love looks like: patient, kind, not jealous or proud. Love protects, trusts, hopes, and never gives up. This is how God loves us and how we should love others.', 'Love is patient, love is kind. It does not envy, it does not boast.', '["What are some things love does?", "What are some things love doesn''t do?", "Who shows you this kind of love?"]', 'Make a "Love Is..." poster with words and pictures.', 'Lord, teach me to love like You love - patient and kind.'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'intermediate', 'In a church fighting over spiritual gifts, Paul shows them something better: love. He describes love with 15 characteristics - mostly about what love DOESN''T do (envy, boast, be rude). Love focuses on others, not self.', 'Love is patient, love is kind; love does not envy or boast; it is not arrogant or rude.', '["Why was Paul writing about love to this church?", "Which characteristic is hardest for you?", "How is this different from romantic love in movies?"]', 'Rate yourself honestly on each characteristic. Pick one to work on.', 'Father, show me where my love falls short. Help me grow in these areas.'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'advanced', 'The "love chapter" isn''t primarily about marriage but about church community. Sandwiched between discussions of spiritual gifts (ch. 12, 14), Paul argues love is the superior way. The description is remarkably active - love is what you DO, not just what you feel.', 'Love is patient, love is kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way.', '["How does context in 1 Corinthians shape interpretation?", "Why are most characteristics negative (what love doesn''t do)?", "How does this challenge sentimental views of love?"]', 'Replace "love" with "I" and read it as a self-examination.', 'Jesus, You are the perfect embodiment of this love. Form me in Your image.'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'young_adult', 'Paul''s hymn to love addresses a church valuing spectacular gifts over character. The Greek ἀγάπη describes choice-based, sacrificial love. Each characteristic confronts Corinthian problems: rivalry, arrogance, divisions. This love is cruciform - it looks like Jesus.', 'Love is patient, love is kind; love does not envy or boast; it is not arrogant or rude.', '["How does each characteristic address Corinthian issues?", "What''s the relationship between love and spiritual gifts?", "How is this counter-cultural today?"]', 'Study 1 Corinthians 12-14 as a unit on gifts and love.', 'Lord, may my pursuit of gifts never outpace my practice of love.'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'adult', 'The verb forms are predominantly present tense, indicating ongoing action. Paul personifies ἀγάπη, giving love active agency. The seven negative statements (οὐ + verb) dominate, suggesting love is defined by restraint. The crescendo in v.7 uses πάντα four times.', 'ἡ ἀγάπη μακροθυμεῖ, χρηστεύεται ἡ ἀγάπη, οὐ ζηλοῖ, οὐ περπερεύεται, οὐ φυσιοῦται', '["How does Paul''s use of virtue/vice lists inform this passage?", "What is the relationship between love and eschatology (v.8-13)?", "How does this passage function rhetorically in the letter?"]', 'Compare with the fruit of the Spirit (Gal 5:22-23) and other Pauline virtue lists.', 'God of love, form in me the character of Christ through Your Spirit.'),
('133bfedc-88fe-4c3b-8c3d-cec5d80d3fb7', 'scholarly', 'The asyndetic list creates rhetorical force. μακροθυμεῖ (long-suffering) and χρηστεύεται (act kindly) are hapax in NT. The phrase οὐ ζηλοῖ may address Corinthian "zeal" for gifts. The structure moves from positive (2 verbs) to negative (8 statements) to positive climax (4 πάντα clauses).', 'ἡ ἀγάπη μακροθυμεῖ χρηστεύεται ἡ ἀγάπη οὐ ζηλοῖ', '["How does the hymnic structure affect interpretation?", "What is the relationship to Stoic and Jewish virtue traditions?", "How does this chapter function in Paul''s argument about spiritual gifts?"]', 'Analyze the chiastic structure and its rhetorical function.', 'Lord, illuminate Your word as I study the nature of divine love.');

-- The Beatitudes - Matthew 5:3-12
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'picture', 'Jesus tells us who is really happy: people who need God, kind people, and peacemakers!', 'Blessed are the peacemakers.', '["What makes you happy?", "What is a peacemaker?", "How can you be kind?"]', 'Draw a picture of yourself being a peacemaker.', 'Jesus, help me be a peacemaker and make You happy!'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'early_reader', 'Jesus taught His followers what it means to be truly blessed (deeply happy). It''s not about being rich or popular. It''s about needing God, being gentle, working for peace, and following God even when it''s hard.', 'Blessed are the poor in spirit: for theirs is the kingdom of heaven. Blessed are they that mourn: for they shall be comforted.', '["What does blessed mean?", "Why are the poor in spirit blessed?", "Which beatitude do you like best?"]', 'Make a Beatitude poster with your favorite blessing.', 'Dear Jesus, teach me what it means to be truly blessed.'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'intermediate', 'The Beatitudes open Jesus'' Sermon on the Mount. Each "blessed" statement flips worldly values upside down. The poor, the mourning, and the persecuted are called blessed - not because suffering is good, but because God''s kingdom brings reversal and hope.', 'Blessed are the poor in spirit: for theirs is the kingdom of heaven.', '["How are the Beatitudes counter-cultural?", "What does ''poor in spirit'' mean?", "How do the Beatitudes connect to God''s kingdom?"]', 'Rewrite each beatitude in your own words for today.', 'Lord, shape my heart to value what You value.'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'advanced', 'The Beatitudes establish the ethical foundation of Jesus'' kingdom teaching. They describe both present reality and future hope (already/not yet). The structure moves from spiritual conditions (poor in spirit, mourn) to active righteousness (peacemakers, persecuted).', 'Blessed are the poor in spirit: for theirs is the kingdom of heaven. Blessed are the meek: for they shall inherit the earth.', '["How do the Beatitudes function as kingdom ethics?", "What is the relationship between present and future blessings?", "How do you embody these in daily life?"]', 'Study the Old Testament background of each beatitude.', 'King Jesus, align my heart with the values of Your kingdom.'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'young_adult', 'The μακάριοι (blessed) statements draw on Jewish wisdom tradition but radically redefine blessing. Jesus pronounces divine favor on those society dismisses. The progression may form a character arc - from recognizing spiritual poverty to enduring persecution.', 'Blessed are the poor in spirit: for theirs is the kingdom of heaven.', '["How do the Beatitudes subvert cultural values?", "What is the relationship between Beatitudes and discipleship?", "How does persecution relate to blessing?"]', 'Compare with Luke''s Beatitudes (Luke 6:20-26) and analyze differences.', 'Rabbi Jesus, teach me the way of blessedness in Your kingdom.'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'adult', 'The term μακάριος describes objective state of blessing rather than subjective happiness. The πτωχοὶ τῷ πνεύματι (poor in spirit) echoes the Isaian anawim. The present tense ἐστιν for kingdom bookends (v.3, 10) while future verbs describe other blessings.', 'μακάριοι οἱ πτωχοὶ τῷ πνεύματι, ὅτι αὐτῶν ἐστιν ἡ βασιλεία τῶν οὐρανῶν', '["How does Matthew''s presentation differ from Luke''s?", "What is the Old Testament background for each beatitude?", "How do the Beatitudes function in Matthew''s structure?"]', 'Analyze the chiastic structure and verbal patterns.', 'Father, may the Beatitudes shape my character and community.'),
('e20c51dd-dd8a-41b4-bbc3-d2e63284b60b', 'scholarly', 'The μακάριος formula draws on wisdom macarisms. The ὅτι clauses provide ground for blessedness. The inclusio of present tense ἐστιν (v.3, 10) with βασιλεία τῶν οὐρανῶν frames the unit. The shift to second person plural in v.11-12 personalizes the final beatitude.', 'μακάριοι οἱ πτωχοὶ τῷ πνεύματι ὅτι αὐτῶν ἐστιν ἡ βασιλεία τῶν οὐρανῶν', '["What is the form-critical classification of beatitudes?", "How does this passage relate to Q material?", "What is the intertextual relationship with Isaiah 61?"]', 'Compare synoptic versions and analyze redactional theology.', 'Lord of wisdom, grant understanding of Your inaugural discourse.');

-- Remaining passages continue in same pattern...
-- Living Sacrifice - Romans 12:1-2
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'picture', 'Give your whole self to God like a special gift! Let Him change how you think!', 'Present your bodies a living sacrifice.', '["What is a gift you''ve given?", "How can you give yourself to God?", "What does God want to change?"]', 'Draw yourself as a gift wrapped up for God.', 'God, I give myself to You today!'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'early_reader', 'Paul says to give our whole lives to God as a gift. Don''t copy what everyone else does. Let God change how you think so you know what''s truly good.', 'Present your bodies a living sacrifice, holy, acceptable unto God. Be not conformed to this world.', '["What does it mean to be a living sacrifice?", "Why shouldn''t we copy the world?", "How does God change us?"]', 'Write one way you will give yourself to God this week.', 'Lord, change how I think. Help me follow You, not the crowd.'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'intermediate', 'After 11 chapters explaining God''s mercy, Paul says: "Therefore..." Our response to grace is total surrender. We offer ourselves as living sacrifices - not dead like Old Testament offerings, but alive and active. This requires mental transformation, not just behavior modification.', 'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service.', '["How does ''therefore'' connect to chapters 1-11?", "What does a living sacrifice look like?", "How is mind renewal different from just trying harder?"]', 'Identify one area where you''re being conformed to the world.', 'Father, I offer myself to You. Renew my mind to know Your good will.'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'advanced', 'Romans 12:1-2 transitions from doctrine to practice. The "mercies of God" (οἰκτιρμῶν) summarize Romans 1-11. "Living sacrifice" is an oxymoron - sacrifices died. But Christian worship is embodied, daily, ongoing. The passive "be transformed" (μεταμορφοῦσθε) indicates Spirit-empowered change.', 'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God.', '["How does this passage define true worship?", "What''s the difference between conforming and transforming?", "What is the ''renewing of your mind''?"]', 'Study how Romans 12-16 applies the theology of Romans 1-11.', 'Holy God, transform me from the inside out by Your Spirit.'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'young_adult', 'Paul''s exhortation is based on (διά) God''s mercies - grace motivates obedience. The σῶμα (body) represents the whole person. "Living sacrifice" paradoxically combines death (surrender) and life (active service). Mind renewal is the mechanism of transformation.', 'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice.', '["How does gospel indicative shape moral imperative?", "What does embodied worship look like today?", "How do you practically renew your mind?"]', 'Compare with Galatians 5 on flesh vs. Spirit.', 'Lord, help me live as a continuous offering of worship to You.'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'adult', 'The aorist infinitive παραστῆσαι (present) suggests decisive offering. λογικὴν λατρείαν is disputed: "reasonable/logical worship" or "spiritual worship." The present imperative μεταμορφοῦσθε indicates ongoing process. δοκιμάζειν means to test and approve.', 'παραστῆσαι τὰ σώματα ὑμῶν θυσίαν ζῶσαν ἁγίαν εὐάρεστον τῷ θεῷ, τὴν λογικὴν λατρείαν ὑμῶν', '["How should λογικὴν λατρείαν be translated?", "What is the relationship between body offering and mind renewal?", "How does this compare with Old Testament sacrifice?"]', 'Study the concept of λογικός in Hellenistic philosophy and early Christianity.', 'God of mercy, receive my embodied worship and renew my mind.'),
('59f7adfb-62cc-45fa-936d-8f8652a8a779', 'scholarly', 'The παρακαλῶ οὖν formula marks major transition. The prepositional phrase διὰ τῶν οἰκτιρμῶν grounds exhortation in previous argument. The θυσίαν ζῶσαν phrase creates oxymoron. The συσχηματίζεσθε/μεταμορφοῦσθε contrast echoes morphological language in 2 Corinthians 3:18.', 'παρακαλῶ οὖν ὑμᾶς ἀδελφοί διὰ τῶν οἰκτιρμῶν τοῦ θεοῦ', '["What is the rhetorical function of παρακαλῶ?", "How does this passage relate to Greco-Roman moral philosophy?", "What is the eschatological context of ''this age''?"]', 'Analyze the transition from Romans 11:36 to 12:1.', 'Father, illuminate Paul''s call to transformed living.');

-- Fruit of the Spirit - Galatians 5:22-23
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('c167b022-6ebc-4259-9042-98261576c9ec', 'picture', 'God''s Spirit grows good things in us like love, joy, peace, and kindness - like fruit on a tree!', 'The fruit of the Spirit is love, joy, peace.', '["What is your favorite fruit?", "How can you show love?", "What makes you joyful?"]', 'Draw a tree with fruits labeled with the Spirit''s fruits.', 'Holy Spirit, grow good fruit in me!'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'early_reader', 'When God''s Spirit lives in us, He grows beautiful fruit in our hearts: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. These aren''t things we force - the Spirit grows them!', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.', '["How many fruits are listed?", "Which one do you need more of?", "How does the Spirit grow fruit in us?"]', 'Make a fruit salad and talk about each spiritual fruit.', 'Holy Spirit, help me let You grow these fruits in my life.'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'intermediate', 'Paul contrasts the "works of the flesh" (things we produce ourselves) with the "fruit of the Spirit" (what God produces in us). Notice it''s singular - fruit, not fruits. These nine qualities are one unified cluster growing from a life connected to Christ.', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance: against such there is no law.', '["Why is it ''fruit'' (singular) not ''fruits''?", "How is fruit different from works?", "What does ''against such there is no law'' mean?"]', 'Identify which fruit is strongest and weakest in your life.', 'Spirit of God, produce Your fruit in me as I stay connected to Jesus.'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'advanced', 'The fruit (καρπός, singular) suggests organic unity. These nine virtues aren''t independently achieved but collectively produced by the Spirit. The list may have structure: love as foundation, joy-peace (internal), patience-kindness-goodness (relational), faithfulness-gentleness-self-control (character).', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.', '["How does this contrast with the works of the flesh?", "What is the relationship between human effort and Spirit production?", "Why does Paul end with ''against such there is no law''?"]', 'Journal about how each fruit addresses a corresponding work of the flesh.', 'Holy Spirit, I cannot manufacture this fruit. Produce it in me as I abide in Christ.'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'young_adult', 'In the context of Galatians'' law vs. grace argument, this passage shows that Spirit-led living produces what law could not. The virtues listed would have been recognized in Hellenistic moral philosophy, but Paul attributes them to divine agency, not human effort.', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.', '["How does this passage fit Galatians'' overall argument?", "What''s the relationship between fruit and freedom?", "How do you ''keep in step with the Spirit'' (v.25)?"]', 'Compare with Colossians 3:12-17 for another virtue list.', 'Spirit, help me walk in step with You, producing fruit that glorifies Christ.'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'adult', 'The singular καρπὸς contrasts with plural ἔργα (works) of the flesh. ἀγάπη leads the list, governing the rest. The final phrase κατὰ τῶν τοιούτων οὐκ ἔστιν νόμος may be ironic: law exists to restrain evil, but these virtues need no restraint.', 'ὁ δὲ καρπὸς τοῦ πνεύματός ἐστιν ἀγάπη χαρά εἰρήνη μακροθυμία χρηστότης ἀγαθωσύνη πίστις πραΰτης ἐγκράτεια', '["How does this relate to Paul''s law theology in Galatians?", "What is the rhetorical function of the vice/virtue lists?", "How do these virtues relate to Christ''s character?"]', 'Study the flesh/Spirit antithesis throughout Galatians.', 'Spirit of Christ, form me in the image of the Son.'),
('c167b022-6ebc-4259-9042-98261576c9ec', 'scholarly', 'The πνεῦμα/σάρξ antithesis structures Galatians 5:13-26. The καρπός singular may emphasize organic unity. The nine qualities may reflect triadic structure. The phrase κατὰ τῶν τοιούτων οὐκ ἔστιν νόμος connects to Galatians'' νόμος discussion.', 'ὁ δὲ καρπὸς τοῦ πνεύματός ἐστιν ἀγάπη χαρά εἰρήνη', '["What is the structure of the vice/virtue lists?", "How do these lists relate to Hellenistic ethics?", "What is the eschatological dimension of walking by Spirit?"]', 'Analyze the πνεῦμα/σάρξ contrast across Pauline literature.', 'Lord, illumine the fruit of Your Spirit in my study.');

-- Continue with remaining 12 passages...
-- Lamp to My Feet - Psalm 119:105
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'picture', 'God''s Word is like a flashlight that shows us where to walk in the dark!', 'Thy word is a lamp unto my feet.', '["Have you used a flashlight in the dark?", "How does light help you see?", "How is the Bible like a light?"]', 'Use a flashlight in a dark room and talk about how the Bible guides us.', 'Thank you God for Your Word that shows me the way!'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'early_reader', 'The Bible is like a lamp for our feet - it helps us see where to walk so we don''t trip. Without God''s Word, we''d be walking in the dark!', 'Thy word is a lamp unto my feet, and a light unto my path.', '["What happens when you walk in the dark?", "How does the Bible guide us?", "What are some ways to use God''s Word?"]', 'Decorate a paper lantern with the verse on it.', 'Lord, help me follow Your Word like a path lit up at night.'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'intermediate', 'This famous verse comes from Psalm 119, the longest psalm and chapter in the Bible - all about loving God''s Word. The imagery of lamp and light shows Scripture provides guidance for daily decisions, not just distant destinations.', 'Thy word is a lamp unto my feet, and a light unto my path.', '["Why is Scripture compared to light?", "What''s the difference between lamp for feet and light for path?", "How do you let Scripture guide you?"]', 'Memorize this verse and practice reciting it in the dark!', 'Father, open my eyes to see the guidance in Your Word.'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'advanced', 'Psalm 119 is an acrostic poem celebrating Torah. "Lamp to my feet" suggests immediate, close guidance (like an oil lamp lighting just the next step). "Light to my path" may suggest broader direction. Both emphasize Scripture''s practical guidance for life.', 'Thy word is a lamp unto my feet, and a light unto my path.', '["How does this verse fit within Psalm 119''s structure?", "What is the difference between immediate and long-term guidance?", "How do you practice Scripture meditation?"]', 'Read the nun strophe (v.105-112) for context.', 'Lord, illumine my path through Your living Word.'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'young_adult', 'In the ancient world without street lights, a lamp was essential for night travel. This verse assumes a dark world needing illumination. The parallelism (lamp/light, feet/path) may distinguish between immediate decisions and life direction - Scripture guides both.', 'Thy word is a lamp unto my feet, and a light unto my path.', '["What does it mean to walk in darkness spiritually?", "How do you use Scripture for practical guidance?", "What role does community play in applying Scripture?"]', 'Practice lectio divina with this verse for a week.', 'God, in a confusing world, Your Word provides clarity and direction.'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'adult', 'The Hebrew נֵר (lamp) and אוֹר (light) create synonymous parallelism. The נ (nun) strophe explores affliction and deliverance through God''s Word. The term דְּבָרֶךָ (your word) encompasses Torah, prophets, and wisdom literature as sources of divine guidance.', 'נֵר לְרַגְלִי דְבָרֶךָ וְאוֹר לִנְתִיבָתִי', '["What is the function of light imagery in wisdom literature?", "How does this connect to Torah as life-giving instruction?", "How does this verse inform hermeneutics?"]', 'Study light imagery across Psalm 119 (v.18, 105, 130).', 'Lord, may Your Word illuminate my journey in covenant faithfulness.'),
('03d8fd09-74d2-449a-93d3-460ac6b0b2b4', 'scholarly', 'The verse forms the opening of the nun strophe. The nouns נֵר and אוֹר represent close and broad illumination. לְרַגְלִי (to my foot) and לִנְתִיבָתִי (to my path) distinguish immediate and extended guidance. The term דָּבָר carries weight from Deuteronomic theology.', 'נֵר לְרַגְלִי דְבָרֶךָ וְאוֹר לִנְתִיבָתִי', '["How does this verse function within the acrostic structure?", "What is the wisdom background of light imagery?", "How does this relate to Proverbs 6:23?"]', 'Analyze the 22-strophe structure and themes of Psalm 119.', 'Lord of wisdom, illumine my study of Your Word.');

-- Great Commission - Matthew 28:19-20
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'picture', 'Jesus says: Go tell everyone about Me! And remember - I''m always with you!', 'I am with you always.', '["Who can you tell about Jesus?", "Is Jesus with you right now?", "How do you feel knowing Jesus is always with you?"]', 'Draw yourself telling a friend about Jesus.', 'Jesus, help me tell others about You. Thank You for being with me!'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'early_reader', 'Jesus told His disciples: Go and teach people everywhere about Me. Baptize them and teach them everything I''ve taught you. And the best part? Jesus promised to be with us forever!', 'Go ye therefore, and teach all nations... lo, I am with you always, even unto the end of the world.', '["What did Jesus tell His disciples to do?", "Who should hear about Jesus?", "What promise does Jesus make?"]', 'Make a paper airplane and write "Tell the world!" on it.', 'Lord Jesus, help me share Your love with people everywhere.'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'intermediate', 'The Great Commission is Jesus'' final command before ascending to heaven. He tells His followers to make disciples of ALL nations - not just their own people. This involves going, baptizing, and teaching. The promise of His presence makes the mission possible.', 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.', '["What does ''make disciples'' mean?", "Why is the trinitarian baptism formula significant?", "How does Jesus'' presence enable the mission?"]', 'Research a missionary and learn how they followed this command.', 'Jesus, use me to make disciples. Thank You for never leaving me.'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'advanced', 'The main verb is "make disciples" (μαθητεύσατε) - going, baptizing, and teaching are participles describing how. "All nations" (πάντα τὰ ἔθνη) breaks ethnic barriers. The trinitarian formula and "all authority" claims shape Christian theology. Christ''s presence echoes Immanuel.', 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you.', '["How does Matthew 28 connect to Matthew 1 (Immanuel)?", "What is the significance of ''all authority''?", "How do you practice disciple-making?"]', 'Study the development of the Great Commission in mission history.', 'Risen Lord, may Your authority and presence empower me to make disciples.'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'young_adult', 'Matthew ends where it begins: Immanuel ("God with us"). The resurrection establishes Jesus'' authority; the commission extends His mission through the church. μαθητεύσατε implies not just conversion but ongoing formation. The church exists for mission.', 'Go ye therefore, and teach all nations... lo, I am with you always, even unto the end of the world.', '["How should this shape church identity and practice?", "What''s the relationship between evangelism and discipleship?", "How do you participate in the Great Commission locally and globally?"]', 'Evaluate your church''s practices against this commission.', 'Lord, align my life with Your mission to all nations.'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'adult', 'The aorist imperative μαθητεύσατε carries urgency. πορευθέντες (going), βαπτίζοντες (baptizing), and διδάσκοντες (teaching) describe how disciples are made. The triadic baptismal formula is unique in the NT. The closing promise echoes the presence formulas of Matthew.', 'πορευθέντες οὖν μαθητεύσατε πάντα τὰ ἔθνη βαπτίζοντες αὐτοὺς εἰς τὸ ὄνομα τοῦ πατρὸς καὶ τοῦ υἱοῦ καὶ τοῦ ἁγίου πνεύματος', '["How does this function as Matthew''s climax?", "What is the history of the trinitarian formula?", "How does Matthean ecclesiology relate to mission?"]', 'Compare commissioning scenes across the Gospels and Acts.', 'Lord of harvest, send workers into Your harvest field.'),
('570711bd-588d-40c4-b6b2-fed3cfe3333e', 'scholarly', 'The πᾶσα ἐξουσία claim echoes Daniel 7:14. The structure balances "all authority" - "all nations" - "all things" - "all days." The authenticity of the trinitarian formula is debated. The phrase ἕως τῆς συντελείας τοῦ αἰῶνος uses Matthean eschatological language.', 'πορευθέντες οὖν μαθητεύσατε πάντα τὰ ἔθνη', '["What is the textual history of the trinitarian formula?", "How does this passage function in Matthean Christology?", "What is the relationship to Jewish proselyte practices?"]', 'Analyze the structure and Matthean redaction of this passage.', 'Lord of mission, illuminate Your commission for Your church.');

-- Faith is Substance - Hebrews 11:1
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'picture', 'Faith means being sure about things we can''t see, like God''s promises!', 'Faith is... the evidence of things not seen.', '["Can you see the wind?", "Can you see God?", "How do you know God is real?"]', 'Feel the wind and talk about believing in things we can''t see.', 'God, help me trust in You even though I can''t see You!'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'early_reader', 'Faith means being sure God''s promises are real even though we can''t see them yet. It''s like being certain about things we hope for. The rest of Hebrews 11 shows how people in the Bible lived by this kind of faith.', 'Now faith is the substance of things hoped for, the evidence of things not seen.', '["What is faith?", "How can we be sure about things we can''t see?", "Who are some people who had great faith?"]', 'Make a faith hall of fame poster with Bible heroes.', 'Lord, help me have faith like the heroes in the Bible.'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'intermediate', 'Hebrews 11:1 isn''t a dictionary definition but introduces the chapter by showing what faith does. "Substance" (hypostasis) means foundation or assurance. "Evidence" (elenchos) means proof or conviction. Faith makes future hopes present and invisible realities certain.', 'Now faith is the substance of things hoped for, the evidence of things not seen.', '["What does faith make real in our experience?", "How is faith different from wishful thinking?", "What were the heroes of faith hoping for?"]', 'List things you believe that you can''t prove with your five senses.', 'Father, grow my faith to trust Your promises as if they''re already here.'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'advanced', 'The Greek ὑπόστασις can mean "assurance" (subjective) or "substance/reality" (objective). ἔλεγχος means proof or conviction. This verse introduces the faith hall of fame. These heroes lived as if the promises were present reality, not just future hope.', 'Now faith is the substance of things hoped for, the evidence of things not seen.', '["Is this definition functional or ontological?", "How does faith relate to hope?", "What future realities were the patriarchs living toward?"]', 'Read all of Hebrews 11 and identify common themes.', 'God, may my faith make Your promises real in my daily experience.'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'young_adult', 'Hebrews 11:1 functions as a thesis statement. Faith doesn''t create reality but grasps invisible reality. The ἐλπιζομένων (hoped for things) and πραγμάτων (things/realities) are objective. Faith is the means by which believers participate in what''s not yet visible.', 'Now faith is the substance of things hoped for, the evidence of things not seen.', '["How does faith in Hebrews compare to Paul''s use?", "What is the eschatological dimension of faith?", "How does this apply when hopes are delayed?"]', 'Study the warning passages in Hebrews alongside chapter 11.', 'Lord, sustain my faith when the invisible seems unreal.'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'adult', 'The term ὑπόστασις appears elsewhere in Hebrews for Christ (1:3) and confidence (3:14). Here it likely means "realization" or "actualization." The πραγμάτων (deeds/realities) are objective, not merely subjective hopes. This connects to the realized eschatology of Hebrews.', 'Ἔστιν δὲ πίστις ἐλπιζομένων ὑπόστασις, πραγμάτων ἔλεγχος οὐ βλεπομένων', '["How should ὑπόστασις be translated?", "What is the relationship between faith and eschatology in Hebrews?", "How does this verse function rhetorically?"]', 'Compare with Hebrews 10:38-39 and 12:1-2 for context.', 'Author and Perfecter of faith, ground my hope in Your unseen realities.'),
('40d827c4-5894-4bcd-83b1-9a90869b61b1', 'scholarly', 'The ὑπόστασις has papyrological attestation as "title deed" (Moulton-Milligan), suggesting ownership of future inheritance. The ἔλεγχος can mean subjective conviction or objective proof. The rhetorical function introduces the exempla of faithful living that follows.', 'Ἔστιν δὲ πίστις ἐλπιζομένων ὑπόστασις πραγμάτων ἔλεγχος οὐ βλεπομένων', '["What is the semantic range of ὑπόστασις in Hellenistic Greek?", "How does this verse relate to Platonic epistemology?", "What is the rhetorical function of the exempla catalogue?"]', 'Analyze the structure of Hebrews 11 and its function in the epistle.', 'Lord, grant wisdom as I study the nature of faith.');

-- Consider It Joy - James 1:2-4
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'picture', 'Even hard times can be good because they help us grow strong and trust God more!', 'Count it all joy when ye fall into divers temptations.', '["What makes things hard?", "How do hard things make you stronger?", "Can you be happy when things are hard?"]', 'Lift something heavy and talk about how hard things build strength.', 'God, help me be joyful even when things are hard!'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'early_reader', 'James says to be joyful when we face hard times! Why? Because difficulties test our faith and help us grow patient and strong. God uses tough times to make us more like Him.', 'Count it all joy when ye fall into divers temptations; knowing that the trying of your faith worketh patience.', '["Why should we be joyful in hard times?", "What does testing faith produce?", "How do trials make us complete?"]', 'Write about a hard time that helped you grow.', 'Lord, help me see hard times as opportunities to grow.'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'intermediate', 'James opens his letter with counterintuitive advice: consider trials as joy. The word for "trials" (πειρασμοῖς) can mean tests or temptations. These produce endurance (ὑπομονή), which leads to maturity. The goal isn''t just surviving but becoming complete.', 'Count it all joy when ye fall into divers temptations; knowing that the trying of your faith worketh patience. And let patience have her perfect work.', '["What kind of trials is James talking about?", "What does endurance produce?", "What does it mean to be ''complete, lacking nothing''?"]', 'Journal about how a difficult season produced growth in you.', 'Father, give me perspective to see trials as growth opportunities.'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'advanced', 'James addresses scattered Jewish Christians facing various trials. The aorist imperative ἡγήσασθε demands a decisive choice to consider trials as joy. The testing (δοκίμιον) purifies and proves faith. ὑπομονή isn''t passive waiting but active endurance leading to τέλειος (completeness).', 'Count it all joy when ye fall into divers temptations; knowing that the trying of your faith worketh patience.', '["How does this connect to Old Testament wisdom on suffering?", "What is the relationship between testing and temptation?", "How do you practice ''considering'' trials as joy?"]', 'Compare with Romans 5:3-5 and 1 Peter 1:6-7 on trials.', 'God, produce perseverance in me through trials so I may be complete.'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'young_adult', 'James reflects Jewish wisdom tradition on suffering. πᾶσαν χαράν (pure/complete joy) is emphatic. The logic chain (trials → testing → endurance → completeness) shows purpose in suffering. This isn''t masochism but confidence in divine purpose within trials.', 'Count it all joy when ye fall into divers temptations; knowing that the trying of your faith worketh patience.', '["How does this relate to the problem of suffering?", "What''s the difference between trials that test and trials that tempt?", "How do you develop this perspective practically?"]', 'Study James 1:12-18 for more on testing and temptation.', 'Lord, reshape my perspective on suffering to see Your purposes.'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'adult', 'The πειρασμοῖς ποικίλοις (various trials) acknowledges diverse forms of testing. The δοκίμιον τῆς πίστεως (testing of faith) uses metallurgical language. The progression to τέλειοι καὶ ὁλόκληροι (complete and whole) reflects perfectionist eschatology.', 'Πᾶσαν χαρὰν ἡγήσασθε ἀδελφοί μου ὅταν πειρασμοῖς περιπέσητε ποικίλοις', '["How does James'' use of πειρασμός relate to wisdom tradition?", "What is the rhetorical function of this opening?", "How does this passage relate to the faith/works discussion later?"]', 'Compare with Sirach 2:1-6 for wisdom background.', 'God of wisdom, grant perspective that counts trials as pure joy.'),
('fb5a31b9-aa9d-4f3f-8ae9-f83568e9f673', 'scholarly', 'The address ἀδελφοί μου identifies recipients. περιπέσητε (fall into) suggests unexpected, surrounding trials. The δοκίμιον may mean "testing" or "that which is tested/approved." The ἔργον τέλειον connects to the faith-works theme developed later.', 'Πᾶσαν χαρὰν ἡγήσασθε ἀδελφοί μου ὅταν πειρασμοῖς περιπέσητε ποικίλοις', '["What is the relationship to Jewish diaspora wisdom?", "How does this function in the letter''s structure?", "What is the semantic range of δοκίμιον?"]', 'Analyze the structure of James 1:2-18 as a theological unit.', 'Lord, illuminate the depths of wisdom in Your word.');

-- Spirit of Power - 2 Timothy 1:7
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'picture', 'God doesn''t give us fear! He gives us power, love, and good thinking!', 'God hath not given us the spirit of fear.', '["What makes you scared?", "What does God give us instead of fear?", "How can you be brave?"]', 'Make a paper shield with "Power, Love, Self-Control" on it.', 'God, thank You for giving me power, not fear!'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'early_reader', 'When Timothy was scared, Paul reminded him: God didn''t give you fear! Instead, He gave you power to be strong, love for others, and self-control to make good choices.', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '["Who was Timothy?", "What three things does God give us?", "When do you need this reminder?"]', 'Write "Power, Love, Self-Control" on three cards and keep them in your pocket.', 'Lord, replace my fear with Your power, love, and clear thinking.'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'intermediate', 'Paul wrote to Timothy during a dangerous time for Christians. Timothy may have been timid, so Paul reminds him that fear doesn''t come from God. Instead, God''s Spirit gives us power to serve, love for others, and sound judgment for decisions.', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '["What was Timothy''s situation?", "How do power, love, and self-control connect?", "When do you most need this verse?"]', 'Identify a fear and write how power, love, or self-control addresses it.', 'Father, when fear rises, remind me of what You''ve given me.'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'advanced', 'The Greek δειλίας (cowardice/timidity) contrasts with the Spirit''s gifts. δύναμις (power) enables ministry, ἀγάπη (love) motivates service, σωφρονισμός (self-discipline/sound judgment) guides action. This verse addresses spiritual gifts and character, not just emotions.', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '["How does context inform interpretation?", "What does each gift specifically enable?", "How do these three work together?"]', 'Study 2 Timothy 1:1-14 for the full context of this encouragement.', 'Spirit of God, empower me with power, love, and sound judgment.'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'young_adult', 'Paul writes from prison to his discouraged protégé. The terms may relate to Timothy''s ordination (v.6). δειλία (cowardice) is the only NT use. σωφρονισμός (sound mind/self-control) is also unique. Paul counters cultural shame with divine empowerment.', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '["What was the cultural context of shame and honor?", "How does this relate to v.6 (''fan into flame'')?", "How do you apply this to your fears?"]', 'Identify a ministry fear and apply each gift to it specifically.', 'Lord, fan into flame Your gifts in me. Replace timidity with power.'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'adult', 'The οὐ... ἀλλά structure contrasts negative and positive. πνεῦμα δειλίας may mean "fearful spirit" or "spirit of cowardice." The triad δύναμις, ἀγάπη, σωφρονισμός may connect to gifts, fruit, and governance. This grounds Timothy''s ministry identity.', 'οὐ γὰρ ἔδωκεν ἡμῖν ὁ θεὸς πνεῦμα δειλίας ἀλλὰ δυνάμεως καὶ ἀγάπης καὶ σωφρονισμοῦ', '["How does this relate to Pauline Spirit theology?", "What is the relationship to Timothy''s ordination?", "How do these three gifts structure ministry?"]', 'Compare with 1 Timothy 4:14 and 2 Timothy 1:6 on Timothy''s gift.', 'God of power, strengthen Your servants for courageous ministry.'),
('c923455e-65f7-4a0f-bb91-57adf66dffda', 'scholarly', 'The hapax δειλία and σωφρονισμός deserve attention. δειλία in LXX indicates blameworthy cowardice. σωφρονισμός may mean "self-discipline" or "making sound-minded." The phrase πνεῦμα δειλίας vs. πνεῦμα... δυνάμεως creates the contrast.', 'οὐ γὰρ ἔδωκεν ἡμῖν ὁ θεὸς πνεῦμα δειλίας', '["What is the semantic range of δειλία in Hellenistic Greek?", "How does this relate to Pastoral ecclesiology?", "What is the function in the letter''s argument?"]', 'Analyze the structure of 2 Timothy 1:6-14 as a unit.', 'Lord, illumine Your word as I study ministerial empowerment.');

-- Remaining 4 passages...
-- Fearfully and Wonderfully Made - Psalm 139:14
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'picture', 'God made you special and wonderful! You are amazing!', 'I am fearfully and wonderfully made.', '["Who made you?", "What makes you special?", "How do you know God loves you?"]', 'Draw a picture of yourself and write "God made me wonderful!"', 'Thank You God for making me just right!'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'early_reader', 'The psalm writer thanks God because God made him in an amazing way. Every person is fearfully (with great care) and wonderfully (beautifully) made by God!', 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works.', '["What does fearfully made mean?", "What does wonderfully made mean?", "Why should we praise God for how we''re made?"]', 'Look in a mirror and thank God for three things about how you''re made.', 'Lord, thank You for creating me carefully and beautifully.'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'intermediate', 'Psalm 139 celebrates God''s complete knowledge of us. Verse 14 praises God as Creator. "Fearfully" means with awe and reverence - you are so complex that only God could make you. "Wonderfully" means distinctly and marvelously. Your existence prompts praise!', 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.', '["How does God''s creation of you lead to praise?", "What does this teach about human value?", "How do you struggle to believe this about yourself?"]', 'Research one amazing fact about the human body and worship God for it.', 'Creator God, I praise You for the marvel of my existence.'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'advanced', 'In context, David reflects on God''s intimate knowledge (vv.1-6), omnipresence (vv.7-12), and creative work (vv.13-18). "Fearfully" (נוֹרָאוֹת) can mean "awesomely." "Wonderfully" (נִפְלֵיתִי) means uniquely distinct. Human dignity grounds in divine creation.', 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.', '["How does context shape the meaning of this verse?", "What is the relationship between creation and human dignity?", "How does this apply to body image and self-worth?"]', 'Read all of Psalm 139 and trace its theological argument.', 'Creator, when I doubt my worth, remind me I am Your marvelous work.'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'young_adult', 'Psalm 139 is a meditation on divine omniscience and omnipresence culminating in praise for creation. The embryological imagery (vv.13-16) was remarkable for the ancient world. This theological anthropology grounds human dignity in divine intentionality.', 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works.', '["How does this inform ethical issues (abortion, disability, genetics)?", "What is the relationship between creation and divine knowledge?", "How do you internalize this truth?"]', 'Study the creation of humans in Genesis 1-2 and Psalm 8.', 'Lord, shape my self-understanding by Your creative purposes.'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'adult', 'The verbs נוֹרָאוֹת (niphal) and נִפְלֵיתִי (niphal) emphasize divine agency. The נֶפֶשׁ (soul/self) knows this truth deeply. The psalm structure moves from omniscience to omnipresence to creation, showing God''s total intimate involvement with each person.', 'אוֹדְךָ עַל כִּי נוֹרָאוֹת נִפְלֵיתִי נִפְלָאִים מַעֲשֶׂיךָ וְנַפְשִׁי יֹדַעַת מְאֹד', '["How does the psalm structure illuminate v.14?", "What is the relationship between divine knowledge and human dignity?", "How does this inform theological anthropology?"]', 'Compare with Job 10:8-12 and Psalm 8 on human creation.', 'God who formed me, may I know deeply that I am Your wondrous work.'),
('8b08b1cc-de06-4365-bdd4-9efe6e81f50b', 'scholarly', 'The niphal נִפְלֵיתִי is reflexive: "I have been made wonderful." The root פלא connects to God''s wondrous acts. The phrase נוֹרָאוֹת נִפְלֵיתִי may be hendiadys. The psalm''s wisdom and lament elements create unique genre features.', 'אוֹדְךָ עַל כִּי נוֹרָאוֹת נִפְלֵיתִי', '["What is the genre of Psalm 139?", "How does the embryological imagery function?", "What is the relationship to ancient Near Eastern creation texts?"]', 'Analyze the structure and wisdom elements of Psalm 139.', 'Lord, grant insight into Your creative work as I study.');

-- Fear Not - Isaiah 41:10
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('b15f8599-ba12-4263-a557-70daeece48a0', 'picture', 'Don''t be scared! God is with you and He is super strong to help you!', 'Fear thou not; for I am with thee.', '["What are you afraid of?", "Is God stronger than your fears?", "How does God help you?"]', 'Draw yourself with God''s strong hand holding your hand.', 'God, I won''t be afraid because You are with me!'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'early_reader', 'God tells His people: Don''t be afraid! I am with you. Don''t worry! I am your God. I will make you strong and help you. I will hold you up with My powerful right hand!', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.', '["What does God tell us not to do?", "What does God promise to do?", "When do you need God''s strength?"]', 'Trace your hand and write one of God''s promises on each finger.', 'Lord, when I''m scared, remind me You are right here with me.'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'intermediate', 'Isaiah speaks to Israel in exile, feeling abandoned. God gives four assurances: don''t fear, don''t be dismayed. Why? I am with you, I am your God. Then four promises: I will strengthen, help, uphold you with My righteous right hand.', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.', '["What is the historical context?", "How do the four commands relate to the four promises?", "Which promise means most to you now?"]', 'Make a bookmark with the four promises listed.', 'Faithful God, Your promises overcome my fears. Help me trust You fully.'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'advanced', 'This Salvation Oracle addresses exiled Israel with classic "fear not" formula. The participial structure (מִבְּצֵר - strengthening, עָזַר - helping, תָמַךְ - upholding) indicates ongoing divine action. "Righteous right hand" combines power (right hand) with covenant faithfulness (righteousness).', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.', '["How does the oracle form shape interpretation?", "What is the significance of the right hand imagery?", "How does righteousness relate to salvation?"]', 'Study the "fear not" oracles in Isaiah 40-55.', 'Covenant God, Your right hand upholds me in every circumstance.'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'young_adult', 'Deutero-Isaiah addresses exiles with assurance. The "fear not" oracle form appears throughout (41:10, 13, 14; 43:1, 5; 44:2, 8). God counters fear with presence ("I am with you"), identity ("I am your God"), and action ("I will strengthen, help, uphold").', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', '["How does exile context shape the message?", "What is the literary function of fear not oracles?", "How do you apply this to modern anxieties?"]', 'Study the Servant Songs alongside the fear not oracles.', 'God of Israel, Your presence is my confidence against fear.'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'adult', 'The אַל־תִּירָא formula introduces the oracle of salvation. The כִּי clauses provide grounds. The first-person divine speech with emphatic אֲנִי reinforces God''s personal involvement. The בִּימִין צִדְקִי (right hand of my righteousness) is distinctive Isaianic language.', 'אַל־תִּירָא כִּי עִמְּךָ־אָנִי אַל־תִּשְׁתָּע כִּי־אֲנִי אֱלֹהֶיךָ', '["What is the form-critical classification?", "How does the divine speech pattern function?", "What is the theological significance of divine righteousness here?"]', 'Compare with other Isaianic fear not oracles.', 'YHWH, I trust Your righteous right hand to uphold me.'),
('b15f8599-ba12-4263-a557-70daeece48a0', 'scholarly', 'The אַל־תִּירָא + כִּי + divine presence formula is characteristic of prophetic salvation oracles. The verb שׁעה (look anxiously) is rare. The threefold first-person declarations (אֲנִי) emphasize divine involvement. צֶדֶק in Deutero-Isaiah has soteriological dimensions.', 'אַל־תִּירָא כִּי עִמְּךָ־אָנִי', '["What is the Gattung of fear not oracles?", "How does צֶדֶק function in Deutero-Isaiah?", "What is the relationship to ancient Near Eastern assurance formulas?"]', 'Analyze all fear not oracles in Isaiah 40-55.', 'Lord, illuminate Your word of assurance to Your people.');

-- Work as Unto the Lord - Colossians 3:23-24
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('bc358bb3-66ea-40e9-9226-517b994a3809', 'picture', 'When you work, do your best like you''re doing it for Jesus!', 'Do it heartily, as to the Lord.', '["What work do you do?", "How would you work if Jesus was watching?", "Jesus IS watching - does that change how you work?"]', 'Do a chore really well today as a gift to Jesus!', 'Jesus, help me do everything for You!'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'early_reader', 'Whatever job you do, work at it with all your heart like you''re working for Jesus, not just for people. Jesus will reward you for your hard work!', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men; knowing that of the Lord ye shall receive the reward.', '["What does it mean to work heartily?", "Who are we really working for?", "What reward will Jesus give?"]', 'Pick a job and do it as if Jesus asked you personally.', 'Lord, help me remember I''m working for You in everything I do.'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'intermediate', 'Paul writes to slaves about their work, but the principle applies to everyone. Our motivation changes everything: we''re not working to please people but to honor Christ. Even mundane tasks become worship when done for the Lord.', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men; knowing that of the Lord ye shall receive the reward of the inheritance.', '["How does this transform boring or difficult work?", "What does ''heartily'' mean?", "How does the reward motivate you?"]', 'For one day, mentally dedicate each task to Jesus before doing it.', 'Father, transform my attitude toward work. I do it all for You.'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'advanced', 'This instruction comes in the household codes section. Paul doesn''t abolish slavery but transforms it from within: the true Master is Christ, the true reward is inheritance. The phrase "from the soul" (ἐκ ψυχῆς) means wholehearted, not grudging obedience.', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men; knowing that of the Lord ye shall receive the reward of the inheritance.', '["How does Paul address unjust systems?", "What is the eschatological motivation for work?", "How does this apply to modern employment?"]', 'Evaluate your work attitude: is it people-pleasing or Lord-serving?', 'Lord Jesus, You are my true Master. I work to honor You.'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'young_adult', 'The ὅ τι ἐὰν ποιῆτε (whatever you do) universalizes the principle. ἐκ ψυχῆς (from the soul) indicates genuine motivation. The κύριος wordplay (human lord/the Lord Christ) reframes service. The inheritance reward transcends earthly compensation.', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.', '["How does this theology of work shape vocation?", "What is the relationship between justice and submission?", "How do you practice working ''unto the Lord''?"]', 'Study the household codes in Colossians, Ephesians, and 1 Peter.', 'Lord Christ, may all my work be genuine worship of You.'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'adult', 'The phrase ἐκ ψυχῆς ἐργάζεσθε (work from the soul) parallels "with goodwill" in Ephesians 6:7. The ἀνταπόδοσιν τῆς κληρονομίας (recompense of the inheritance) assures slaves of equal reward with free. τῷ κυρίῳ Χριστῷ δουλεύετε makes Christ the ultimate master.', 'ὃ ἐὰν ποιῆτε ἐκ ψυχῆς ἐργάζεσθε ὡς τῷ κυρίῳ καὶ οὐκ ἀνθρώποις', '["How does this passage function within Pauline ethics?", "What is the eschatological dimension of inheritance language?", "How should this inform Christian business ethics?"]', 'Compare Colossians 3:22-4:1 with Ephesians 6:5-9 and Philemon.', 'Lord Christ, I serve You in all my earthly service.'),
('bc358bb3-66ea-40e9-9226-517b994a3809', 'scholarly', 'The indefinite relative clause ὃ ἐὰν ποιῆτε generalizes instruction. The dative τῷ κυρίῳ creates ambiguity: human lord or Christ? Verse 24 resolves: τῷ κυρίῳ Χριστῷ. The κληρονομία language connects to OT inheritance promises now extended to slaves.', 'ὃ ἐὰν ποιῆτε ἐκ ψυχῆς ἐργάζεσθε', '["How do the household codes function socially?", "What is the relationship between this and Philemon?", "How does inheritance theology apply to slaves?"]', 'Analyze the structure and function of Haustafel material.', 'Lord, illuminate the social ethics of Your word.');

-- Cast Your Cares - 1 Peter 5:7
INSERT INTO passage_levels (passage_id, reading_level, summary, key_verse, discussion_questions, activity_suggestion, prayer_prompt) VALUES
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'picture', 'Give all your worries to God because He loves you so much!', 'Casting all your care upon him.', '["What do you worry about?", "Can you give worries to God?", "Does God love you?"]', 'Write worries on paper and put them in a "God''s care" box.', 'God, I give You all my worries. Thank You for loving me!'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'early_reader', 'Peter tells us to throw all our worries onto God like throwing a ball to someone else. Why can we do this? Because God cares about you so much!', 'Casting all your care upon him; for he careth for you.', '["What does casting mean?", "What worries can you give to God?", "How do you know God cares for you?"]', 'Throw a ball while saying worries, then catch it saying "God cares!"', 'Lord, I throw all my worries to You. Thank You for caring about me.'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'intermediate', 'Peter writes to Christians facing persecution. The word for "cast" means to throw upon - it''s decisive action, not passive hoping. All anxieties - big and small - can be transferred to God because (here''s the reason) He genuinely cares about you personally.', 'Casting all your care upon him; for he careth for you.', '["What were Peter''s readers going through?", "What does ''all'' mean here?", "How do you practically cast cares on God?"]', 'Make a list of worries and pray through each one, releasing it to God.', 'Caring Father, I actively release my anxieties to You right now.'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'advanced', 'The aorist participle ἐπιρίψαντες (having cast) suggests decisive action prerequisite to humility (v.6). μέριμνα (anxiety/care) covers all distracting worries. The ὅτι clause grounds the action: God''s care (μέλει) is personal and ongoing (present tense).', 'Casting all your care upon him; for he careth for you.', '["How does this connect to v.6 (humility)?", "What is the relationship between worry and pride?", "What does God''s care look like?"]', 'Study 1 Peter 5:5-11 as a unit on humility and suffering.', 'Lord, humility means trusting You with my anxieties. I cast them on You.'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'young_adult', 'This verse echoes Psalm 55:22 (LXX). The participial phrase connects to the imperative "humble yourselves" - casting care is an act of humility. The care/cares wordplay (μέριμνα/μέλει) emphasizes exchange: we release worry, He takes concern.', 'Casting all your care upon him; for he careth for you.', '["How does casting cares relate to humility?", "What is the OT background?", "How do you distinguish casting cares from passivity?"]', 'Compare with Philippians 4:6-7 and Matthew 6:25-34 on anxiety.', 'God, I humbly acknowledge I cannot carry these burdens alone.'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'adult', 'The verb ἐπιρίπτω (throw upon) appears in Psalm 55:23 LXX (54:23). The πᾶσαν (all) is emphatic. The impersonal μέλει αὐτῷ περὶ ὑμῶν (it matters to Him concerning you) personalizes divine care. This grounds the ethical exhortation of v.6.', 'πᾶσαν τὴν μέριμναν ὑμῶν ἐπιρίψαντες ἐπ᾽ αὐτόν ὅτι αὐτῷ μέλει περὶ ὑμῶν', '["How does this function in the letter''s argument?", "What is the syntactical relationship to v.6?", "How does this address suffering communities?"]', 'Compare with Psalm 55:22 LXX and analyze Petrine use of OT.', 'Faithful God, Your care for me enables me to release all anxiety.'),
('1873e5d5-1007-43af-aaa8-9c857d8487ec', 'scholarly', 'The participial phrase ἐπιρίψαντες... ἐπ᾽ αὐτόν depends on ταπεινώθητε (v.6). The article τὴν μέριμναν makes anxiety definite - "your particular anxiety." The construction μέλει περὶ with genitive indicates the object of care. Psalm 55:23 LXX: ἐπίρριψον ἐπὶ κύριον τὴν μέριμνάν σου.', 'πᾶσαν τὴν μέριμναν ὑμῶν ἐπιρίψαντες ἐπ᾽ αὐτόν', '["What is the textual relationship to Psalm 55 LXX?", "How does the participle function syntactically?", "What is the Petrine theology of suffering?"]', 'Analyze the structure and sources of 1 Peter 5:5-11.', 'Lord, grant wisdom as I study Your word of comfort to suffering saints.');
